SPORTYBET_TEAMS: dict[str, str] = {
    "07 Vestur Sorvagur": "07 Vestur Sorvagur",
    "1 FC Kaiserslautern": "1 FC Kaiserslautern",
    "1 FC Nuremberg": "1 FC Nuremberg",
    "1. FC Magdeburg": "1. FC Magdeburg",
    "1. FC Phonix Lubeck": "1. FC Phonix Lubeck",
    "1. FC Saarbrucken": "1. FC Saarbrucken",
    "AB Argir": "AB Argir",
    "AC Horsens": "AC Horsens",
    "AC Milan": "Milan",
    "AC Oulu": "AC Oulu",
    "ADO Den Haag": "ADO Den Haag",
    "AE Kifisia FC": "AE Kifisia FC",
    "AEK Athens": "AEK Athens FC",
    "AFC Wimbledon": "AFC Wimbledon",
    "AGF Aarhus": "AGF Aarhus",
    "AIK DFF": "AIK DFF",
    "AIK Stockholm": "AIK",
    "APO Levadiakos FC": "APO Levadiakos FC",
    "AS Trencin": "AS Trencin",
    "AZ Alkmaar": "Alkmaar",
    "Aalesunds FK": "Aalesunds FK",
    "Aarhus": "AGF Aarhus",
    "Aberdeen": "Aberdeen",
    "Academico Viseu": "Academico de Viseu FC",
    "Academico de Viseu FC": "Academico de Viseu FC",
    "Airbus UK Broughton": "Airbus UK",
    "Ajax": "Ajax",
    "Ajax Amsterdam": "Ajax Amsterdam",
    "Akhmat": "RFK Akhmat Grozny",
    "Akron Tolyatti": "Akron Tolyatti",
    "Alanyaspor": "Alanyaspor",
    "Alashkert": "FC Alashkert",
    "Alaves": "Alaves",
    "Alkmaar": "Alkmaar",
    "Aluminij Kidricevo": "Aluminij Kidricevo",
    "Alverca Futebol": "Alverca",
    "Amed": "Amed",
    "Amed Sportif Faaliyetler": "Amed Sportif Faaliyetler",
    "Ammanford": "Ammanford",
    "Anderlecht": "RSC Anderlecht",
    "Angers": "Angers",
    "Antwerp": "Royal Antwerp FC",
    "Apollon Limassol": "Apollon Limassol",
    "Ararat": "Ararat Yerevan",
    "Ararat-Armenia": "FC Ararat-Armenia",
    "Aris Thessaloniki": "Aris Thessaloniki",
    "Arminia Bielefeld": "Arminia Bielefeld",
    "Arsenal": "Arsenal",
    "Arsenal Tivat": "Arsenal Tivat",
    "Ascoli Calcio 1898": "Ascoli Calcio 1898",
    "Astana": "Astana",
    "Asteras Tripolis": "Asteras Tripolis",
    "Aston Villa": "Aston Villa",
    "Atalanta": "Atalanta",
    "Atert Bissen": "Atert Bissen",
    "Ath Madrid": "Atletico Madrid",
    "Athletic Bilbao": "Ath Bilbao",
    "Athletic Club": "Athletic Bilbao",
    "Atletico Madrid": "Atletico Madrid",
    "Atromitos": "Atromitos",
    "Atromitos Athinon": "Atromitos Athinon",
    "Augsburg": "Augsburg",
    "Austria Lustenau": "Austria Lustenau",
    "Auxerre": "AJ Auxerre",
    "B36 Torshavn": "B36 Torshavn",
    "BFC Daugavpils": "BFC Daugavpils",
    "BK Häcken": "Hacken",
    "BSC Young Boys": "Young Boys",
    "Bahlinger SC": "Bahlinger SC",
    "Ballkani": "Ballkani",
    "Ballymena United": "Ballymena United",
    "Baltika Kaliningrad": "Baltika Kaliningrad",
    "Balzan": "Balzan FC",
    "Bangor FC": "Bangor FC",
    "Barcelona": "Barcelona",
    "Barnsley FC": "Barnsley FC",
    "Barry Town United": "Barry Town",
    "Barry Town United FC": "Barry Town United FC",
    "Basel": "Basel",
    "Bayer Leverkusen": "Leverkusen",
    "Bayern Munich": "Bayern Munich",
    "Başakşehir": "Başakşehir",
    "Benfica": "Benfica",
    "Besiktas Istanbul": "Besiktas Istanbul",
    "Betis": "Real Betis",
    "Beveren": "KV Waasland-Beveren",
    "Birkirkara": "Birkirkara",
    "Birmingham": "Birmingham City",
    "Birmingham City": "Birmingham City",
    "Birzebbuga St. Peter": "Birzebbuga St. Peter",
    "Birzebbuga St. Peters FC": "Birzebbuga St. Peters FC",
    "Blackburn": "Blackburn Rovers",
    "Blackburn Rovers": "Blackburn Rovers",
    "Blackpool FC": "Blackpool FC",
    "Bnei Sakhnin FC": "Bnei Sakhnin FC",
    "Bochum": "Bochum",
    "Bodo/Glimt": "Bodoe/Glimt",
    "Bodoe/Glimt": "Bodoe/Glimt",
    "Bohemians 1905": "Bohemians 1905",
    "Bologna": "Bologna",
    "Bolton Wanderers": "Bolton",
    "Borac Banja Luka": "FK Borac Banja Luka",
    "Borussia M\xf6nchengladbach": "M'gladbach",
    "Borussia M´gladbach": "Borussia M´gladbach",
    "Botoșani": "FC Botosani",
    "Bournemouth": "Bournemouth",
    "Bradford City FC": "Bradford City FC",
    "Braga": "SC Braga",
    "Brann Bergen": "Brann",
    "Bravo Ljubljana": "Bravo Ljubljana",
    "Brentford": "Brentford",
    "Brest": "Brest",
    "Brighton": "Brighton",
    "Bristol City": "Bristol City",
    "Bristol Rovers": "Bristol Rovers",
    "Briton Ferry": "Briton Ferry",
    "Brondby": "Broendby IF",
    "Buducnost Podgorica": "Buducnost Podgorica",
    "Budućnost Podgorica": "Buducnost Podgorica",
    "Bukovyna Chernivtsi": "Bukovyna Chernivtsi",
    "Burnley": "Burnley",
    "Bălți": "CSF Bălți",
    "CFR Cluj": "CFR 1907 Cluj",
    "CS Universitatea Craiova": "CS Universitatea Craiova",
    "CSF Bălți": "CSF Bălți",
    "CSKA Moscow": "CSKA Moscow",
    "Cadiz": "Cadiz",
    "Caernarfon Town": "Caernarfon Town",
    "Caernarfon Town FC": "Caernarfon Town FC",
    "Cagliari": "Cagliari",
    "Calcio Padova": "Calcio Padova",
    "Cambrian United": "Cambrian United",
    "Cambridge United": "Cambridge United",
    "Cardiff": "Cardiff City",
    "Cardiff City": "Cardiff City",
    "Cardiff Metropolitan University FC": "Cardiff Metropolitan University FC",
    "Carrarese": "Carrarese",
    "Carrick Rangers": "Carrick Rangers",
    "Casa Pia Lisbon": "Casa Pia Lisbon",
    "Caykur Rizespor": "Caykur Rizespor",
    "Celje": "NK Celje",
    "Celta": "Celta",
    "Celta Vigo": "Celta",
    "Celtic": "Celtic",
    "Cercle Brugge": "Cercle Brugge",
    "Cesena FC": "Cesena FC",
    "Charleroi": "Royal Charleroi SC",
    "Charlton Athletic": "Charlton",
    "Chelsea": "Chelsea",
    "Chelsea U21": "Chelsea U21",
    "Cherno More": "Cherno More Varna",
    "Chornomorets": "Chornomorets",
    "Chornomorets Odesa": "Chornomorets",
    "Cliftonville FC": "Cliftonville FC",
    "Club Brugge": "Club Brugge",
    "Coleraine FC": "Coleraine FC",
    "Cologne": "Cologne",
    "Colwyn Bay": "Colwyn Bay",
    "Como": "Como 1907",
    "Como 1907": "Como 1907",
    "Connah's Quay Nomads": "GAP Connah S Quay FC",
    "Connah`s Quay Nomads FC": "Connah`s Quay Nomads FC",
    "Copenhagen": "FC Copenhagen",
    "Corum FK": "Corum FK",
    "Coventry City": "Coventry City",
    "Cremonese": "US Cremonese",
    "Crewe Alexandra": "Crewe Alexandra",
    "Crusaders FC": "Crusaders FC",
    "Crystal Palace": "Crystal Palace",
    "DAC 1904 Dunajská Streda": "Dunajska Streda",
    "Dacia Buiucani": "Dacia-Buiucani",
    "Dacia-Buiucani": "Dacia-Buiucani",
    "Darmstadt": "Darmstadt",
    "Debreceni VSC": "Debreceni VSC",
    "Derby": "Derby County",
    "Derby County": "Derby County",
    "Differdange 03": "FC Differdange 03",
    "Dinamo București": "Dinamo Bucuresti",
    "Dinamo City": "Dinamo Tirana",
    "Dinamo Zagreb": "GNK Dinamo Zagreb",
    "Djurgardens IF DFF": "Djurgardens IF DFF",
    "Djurgårdens IF": "Djurgarden",
    "Doncaster Rovers": "Doncaster Rovers",
    "Dortmund": "Borussia Dortmund",
    "Dunajska Streda": "Dunajska Streda",
    "Dundee": "Dundee",
    "Dundee United": "Dundee United",
    "Dungannon Swifts": "Dungannon Swifts",
    "Dynamo Dresden": "Dynamo Dresden",
    "Dynamo Makhachkala": "Dinamo Makhachkala",
    "Dynamo Moscow": "Dynamo Moscow",
    "ETO FC Gyor": "ETO FC Gyor",
    "Eb/Streymur": "Eb/Streymur",
    "Egnatia": "KF Egnatia Rrogozhine",
    "Eintracht Braunschweig": "Eintracht Braunschweig",
    "Eintracht Frankfurt": "Ein Frankfurt",
    "Eintracht Trier": "Eintracht Trier",
    "Elbasani": "AF Elbasani",
    "Elche": "Elche CF",
    "Elche CF": "Elche CF",
    "Eldense": "Eldense",
    "Empoli": "Empoli",
    "Energie Cottbus": "Energie Cottbus",
    "Epitsentr Kamianets-Podilsky": "Epitsentr",
    "Erzgebirge Aue": "Erzgebirge Aue",
    "Erzurumspor FK": "Erzurumspor FK",
    "Eskilstuna United DFF": "Eskilstuna United DFF",
    "Espanol": "Espanyol",
    "Espanyol": "Espanyol",
    "Estac Troyes": "Troyes",
    "Estoril": "Estoril Praia",
    "Estoril Praia": "Estoril Praia",
    "Estrela Amadora": "Estrela",
    "Etzella Ettelbruck": "Etzella Ettelbruck",
    "Everton": "Everton",
    "Excelsior": "Excelsior Rotterdam",
    "Exeter City": "Exeter City",
    "Eyupspor": "Eyupspor",
    "F91 Dudelange": "F91 Dudelange",
    "FC Aktobe": "FC Aktobe",
    "FC Alashkert Yerevan": "FC Alashkert Yerevan",
    "FC Altai Oskemen": "FC Altai Oskemen",
    "FC Annecy": "FC Annecy",
    "FC Arouca": "Arouca",
    "FC BKMA Yerevan": "FC BKMA Yerevan",
    "FC Balti": "FC Balti",
    "FC Baltika Kaliningrad": "FC Baltika Kaliningrad",
    "FC Baník Ostrava": "Banik Ostrava",
    "FC Basel 1893": "Basel",
    "FC CSKA 1948": "FC CSKA 1948",
    "FC Carl Zeiss Jena": "FC Carl Zeiss Jena",
    "FC Dila Gori": "FC Dila Gori",
    "FC Dinamo Batumi": "FC Dinamo Batumi",
    "FC Dinamo City": "FC Dinamo City",
    "FC Dinamo Minsk": "Dinamo Minsk",
    "FC Drita": "FC Drita",
    "FC Dynamo Kyiv": "Dynamo Kyiv",
    "FC Dynamo-Makhachkala": "FC Dynamo-Makhachkala",
    "FC Fakel Voronezh": "FC Fakel Voronezh",
    "FC Famalicao": "Famalicao",
    "FC Gagra": "FC Gagra",
    "FC Hradec Kralove": "FC Hradec Kralove",
    "FC Hradec Králové": "Hradec Kralove",
    "FC Inter Turku": "FC Inter Turku",
    "FC Irtysh Pavlodar": "FC Irtysh Pavlodar",
    "FC Koper": "FC Koper",
    "FC Lahti": "FC Lahti",
    "FC Lugano": "FC Lugano",
    "FC Luzern": "FC Luzern",
    "FC Meshakhte Tkibuli": "FC Meshakhte Tkibuli",
    "FC Milsami": "FC Milsami",
    "FC Noah Yerevan": "FC Noah Yerevan",
    "FC Ordabasy": "FC Ordabasy",
    "FC Orenburg": "FC Orenburg",
    "FC Pardubice": "Pardubice",
    "FC Politehnica Chisinau": "FC Politehnica Chisinau",
    "FC Pyunik Yerevan": "FC Pyunik Yerevan",
    "FC RFS": "FC RFS",
    "FC Real Sireti": "FC Real Sireti",
    "FC Rosengaard Malmo": "FC Rosengaard Malmo",
    "FC Rostov": "FK Rostov",
    "FC Rustavi": "FC Rustavi",
    "FC ST. Gallen": "FC St. Gallen 1879",
    "FC Samgurali Tskaltubo": "FC Samgurali Tskaltubo",
    "FC Sion": "Sion",
    "FC Slovan Liberec": "Slovan Liberec",
    "FC Spaeri": "FC Spaeri",
    "FC St. Gallen": "FC St. Gallen 1879",
    "FC St. Pauli": "FC St. Pauli",
    "FC Thun": "FC Thun",
    "FC Torino": "Torino",
    "FC Torpedo Kutaisi": "FC Torpedo Kutaisi",
    "FC Twente Enschede W": "FC Twente Enschede W",
    "FC Urartu Yerevan": "FC Urartu Yerevan",
    "FC Vaduz": "FC Vaduz",
    "FC Viktoria Cologne": "FC Viktoria Cologne",
    "FC Winterthur": "Winterthur",
    "FC Wurzburger Kickers": "FC Wurzburger Kickers",
    "FC Yelimai": "FC Yelimai",
    "FC Zhenis": "FC Zhenis",
    "FC Zimbru Chisinau": "FC Zimbru Chisinau",
    "FC Zlín": "Zlin",
    "FC Zurich": "FC Zurich",
    "FC Zürich": "Zurich",
    "FF Jaro": "FF Jaro",
    "FK Akron Tolyatti": "FK Akron Tolyatti",
    "FK Atyrau": "FK Atyrau",
    "FK Auda Riga": "FK Auda Riga",
    "FK Austria Wien": "FK Austria Wien",
    "FK Crvena Zvezda": "Crvena Zvezda",
    "FK Dinamo Moscow": "FK Dinamo Moscow",
    "FK Dukla Prague": "Dukla Prague",
    "FK Jablonec": "Jablonec",
    "FK Jerv": "Jerv",
    "FK Kaspii Aktau": "FK Kaspii Aktau",
    "FK Košice": "FK Košice",
    "FK Krasnodar": "FK Krasnodar",
    "FK Liepaja": "FK Liepaja",
    "FK Mladá Boleslav": "Mlada Boleslav",
    "FK Partizan Belgrade": "FK Partizan Belgrade",
    "FK Rostov": "FK Rostov",
    "FK Rubin Kazan": "FK Rubin Kazan",
    "FK Spartak Moscow": "FK Spartak Moscow",
    "FK Teplice": "Teplice",
    "FK Tukums 2000/TSS": "FK Tukums 2000/TSS",
    "FK Zeleznicar": "Železničar Pančevo",
    "FK Zenit Saint Petersburg": "FK Zenit Saint Petersburg",
    "FS Jelgava": "FS Jelgava",
    "Fakel": "FC Fakel Voronezh",
    "Fakel Voronezh": "Fakel Voronezh",
    "Falkirk": "Falkirk FC",
    "Farul Constanța": "Farul Constanta",
    "Fenerbahce": "Fenerbahce Istanbul",
    "Fenerbahçe": "Fenerbahce Istanbul",
    "Ferencvarosi Budapest": "Ferencvarosi TC",
    "Ferencváros": "Ferencvarosi TC",
    "Feyenoord": "Feyenoord",
    "Feyenoord Rotterdam": "Feyenoord Rotterdam",
    "Fiorentina": "Fiorentina",
    "Fleetwood Town": "Fleetwood Town",
    "Flint Town United": "Flint Town",
    "Floriana": "Floriana",
    "For Sittard": "Fortuna Sittard",
    "Fortuna D": "Fortuna D",
    "Fredrikstad FK": "Fredrikstad",
    "Freiburg": "Freiburg",
    "Frosinone": "Frosinone",
    "Fulham": "Fulham",
    "GAIS": "GAIS",
    "GKS Katowice": "GKS Katowice",
    "GKS Piast Gliwice": "Piast Gliwice",
    "Galatasaray Istanbul": "Galatasaray Istanbul",
    "Gandzasar Kapan FC": "Gandzasar Kapan FC",
    "Gaziantep FK": "Gaziantep FK",
    "Genclerbirligi SK": "Genclerbirligi SK",
    "Genk": "Genk",
    "Genoa": "Genoa",
    "Gent": "Gent",
    "Gençlerbirliği": "Genclerbirligi",
    "Getafe": "Getafe",
    "Gil Vicente Barcelos": "Gil Vicente Barcelos",
    "Girona": "Girona",
    "Glentoran FC": "Glentoran FC",
    "Go Ahead Eagles": "Go Ahead Eagles",
    "Gornik Zabrze": "Gornik Zabrze",
    "Goztepe Izmir": "Goztepe Izmir",
    "Grasshopper Club Zürich": "Grasshopper",
    "Grazer AK 1902": "Grazer AK 1902",
    "Grenoble Foot": "Grenoble Foot",
    "Greuther Furth": "Greuther Furth",
    "Grobinas SC/LFS": "Grobinas SC/LFS",
    "Groningen": "FC Groningen",
    "Guimaraes": "Vitoria de Guimaraes",
    "Győri ETO": "Gyori ETO FC",
    "Gzira United": "Gzira United",
    "HB Torshavn": "HB Torshavn",
    "HJK Helsinki": "HJK Helsinki",
    "HNK Gorica": "HNK Gorica",
    "HNK Hajduk Split": "HNK Hajduk Split",
    "HNK Rijeka": "HNK Rijeka",
    "Hacken Gothenburg W": "Hacken Gothenburg W",
    "Hallescher FC": "Hallescher FC",
    "Halmstads BK": "Halmstad",
    "HamKam": "HamKam",
    "Hamburger SV": "Hamburg",
    "Hammarby IF": "Hammarby",
    "Hamrun Spartans": "Hamrun Spartans",
    "Hansa Rostock": "Hansa Rostock",
    "Hapoel Be'er Sheva": "Hapoel Beer Sheva",
    "Hapoel Beer Sheva": "Hapoel Beer Sheva",
    "Hapoel Ironi Kiryat Shmona": "Ironi Kiryat Shmona",
    "Hapoel Ironi Kiryat Shmona FC": "Hapoel Ironi Kiryat Shmona FC",
    "Hapoel Jerusalem": "Hapoel Hadera",
    "Hapoel Jerusalem FC": "Hapoel Jerusalem FC",
    "Hapoel Petah Tikva": "Maccabi Petah Tikva",
    "Hapoel Petah Tikva FC": "Hapoel Petah Tikva FC",
    "Hapoel Ramat Gan": "Hapoel Katamon",
    "Hapoel Ramat Gan Givatayim FC": "Hapoel Ramat Gan Givatayim FC",
    "Hapoel Tel Aviv FC": "Hapoel Tel Aviv FC",
    "Hapoel Tel-Aviv": "Hapoel Haifa",
    "Harju JK Laagri": "Harju JK Laagri",
    "Haugesund FK": "Haugesund",
    "Haverfordwest County AFC": "Haverfordwest County AFC",
    "Hearts": "Heart of Midlothian FC",
    "Heerenveen": "SC Heerenveen",
    "Heidenheim": "Heidenheim",
    "Hertha": "Hertha",
    "Hibernian": "Hibernian FC",
    "Hibernians FC Paola": "Hibernians FC Paola",
    "Hoffenheim": "Hoffenheim",
    "Holstein Kiel": "Holstein Kiel",
    "Holywell Town": "Holywell Town",
    "Hostert": "US Hostert",
    "Hull City": "Hull City",
    "IF Brommapojkarna": "Brommapojkarna",
    "IF Elfsborg": "Elfsborg",
    "IF Gnistan": "IF Gnistan",
    "IFK Göteborg": "IFK Goteborg",
    "IFK Mariehamn": "IFK Mariehamn",
    "IFK Norrkoping DFK": "IFK Norrkoping DFK",
    "IFK Norrköping": "Norrkoping",
    "IFK Värnamo": "Varbergs",
    "IK Sirius": "Sirius",
    "IK Start": "IK Start",
    "IK Uppsala Fotboll": "IK Uppsala Fotboll",
    "IMT Beograd": "IMT Novi Beograd",
    "Iberia 1999": "FC Iberia 1999",
    "Inter": "Inter Milan",
    "Inter Club de Escaldes": "Inter Club de Escaldes",
    "Inter Milan": "Inter Milan",
    "Ipswich": "Ipswich Town",
    "Ipswich Town": "Ipswich Town",
    "Iraklis 1908": "Iraklis",
    "Ironi Tiberias": "Ironi Tiberias",
    "Istanbul BB": "Istanbul BB",
    "Istra 1961": "Istra 1961",
    "Istra1961": "Istra 1961",
    "Jagiellonia": "Jagiellonia Bialystok",
    "Jeunesse Esch": "AS Jeunesse Esch",
    "Juve Stabia": "Juve Stabia",
    "Juventus": "Juventus",
    "KF Drenica Skenderaj": "KF Drenica Skenderaj",
    "KF Llapi": "KF Llapi",
    "KF Malisheva": "KF Malisheva",
    "KF Vushtrria": "KF Vushtrria",
    "KFUM Oslo": "KFUM",
    "KI Klaksvik": "KI Klaksvik",
    "KKS Lech Poznan": "Lech Poznan",
    "KS Cracovia Krakow": "Cracovia",
    "KV Mechelen": "Yellow-Red KV Mechelen",
    "K\xf6ln": "FC Koln",
    "Kaerjeng 97": "Kaerjeng 97",
    "Kairat Almaty": "FC Kairat Almaty",
    "Kaisar Kyzylorda": "Kaisar Kyzylorda",
    "Kalmar FF": "Kalmar",
    "Karlsruher SC": "Karlsruher SC",
    "Karpaty": "Karpaty",
    "Karpaty Lviv": "Karpaty",
    "Kasimpasa Istanbul": "Kasimpasa Istanbul",
    "Kauno Zalgiris": "FK Kauno Zalgiris",
    "Kauno Žalgiris": "FK Kauno Zalgiris",
    "Kayserispor": "Kayserispor",
    "Kharkiv": "Metalist Kharkiv",
    "Kifisia": "Kifisia",
    "Kilmarnock": "Kilmarnock FC",
    "Kisvarda FC": "Kisvarda FC",
    "Kocaelispor": "Kayserispor",
    "Konyaspor": "Konyaspor",
    "Korona Kielce": "Korona Kielce",
    "Kortrijk": "KV Kortrijk",
    "Košice": "FK Košice",
    "Krasnodar": "FC Krasnodar",
    "Kristianstads DFF": "Kristianstads DFF",
    "Kristiansund BK": "Kristiansund BK",
    "Krylia Sovetov Samara": "Krylia Sovetov",
    "Kryvbas": "Kryvbas KR",
    "Kryvbas KR": "Kryvbas KR",
    "Kryvbas Kryvyi Rih": "Kryvbas KR",
    "Kudrivka": "Kudrivka",
    "Kuopion Palloseura": "Kuopion Palloseura",
    "LASK Linz": "LASK Linz",
    "LKP Motor Lublin": "Motor Lublin",
    "LNZ Cherkasy": "LNZ Cherkasy",
    "Larne": "Larne FC",
    "Las Palmas": "Las Palmas",
    "Lask Linz": "LASK Linz",
    "Lausanne": "Lausanne-Sport",
    "Lausanne-Sport": "Lausanne-Sport",
    "Laval": "Laval",
    "Lazio": "Lazio",
    "Laçi": "Laci",
    "Le Havre": "Le Havre",
    "Le Mans": "Le Mans FC",
    "Le Mans FC": "Le Mans FC",
    "Lech Poznań": "Lech Poznan",
    "Leeds": "Leeds United",
    "Leeds United": "Leeds United",
    "Leganes": "Leganes",
    "Legia": "Legia Warszawa",
    "Leicester": "Leicester",
    "Lens": "RC Lens",
    "Levante": "Levante",
    "Levski Sofia": "PFC Levski Sofia",
    "Leyton Orient London": "Leyton Orient London",
    "Lille": "Lille",
    "Lillestroem": "Lillestroem SK",
    "Lillestrom": "Lillestroem SK",
    "Lillestrøm": "Lillestroem SK",
    "Limavady United FC": "Limavady United FC",
    "Lincoln City": "Lincoln City",
    "Lincoln Red Imps": "Lincoln Red Imps",
    "Linfield FC": "Linfield FC",
    "Linz": "LASK Linz",
    "Liverpool": "Liverpool",
    "Livyi Bereh": "Livyi Bereh",
    "Livyi Bereh Kyiv": "Livyi Bereh",
    "Llandudno": "Llandudno",
    "Llandudno FC": "Llandudno FC",
    "Lokomotiv Moscow": "Lokomotiv",
    "Lommel": "Lommel SK",
    "Lorient": "Lorient",
    "Ludogorets Razgrad": "Ludogorets",
    "Lugano": "FC Lugano",
    "Luneburger SK Hansa": "Luneburger SK Hansa",
    "Luton": "Luton",
    "Luzern": "FC Luzern",
    "Lyngby": "Lyngby BK",
    "Lyon": "Lyon",
    "MFk Karviná": "Karvina",
    "MSV Duisburg": "MSV Duisburg",
    "MTK Budapest": "MTK Budapest",
    "Maccabi Haifa FC": "Maccabi Haifa FC",
    "Maccabi Netanya FC": "Maccabi Netanya FC",
    "Maccabi Petah Tikva FC": "Maccabi Petah Tikva FC",
    "Maccabi Tel Aviv FC": "Maccabi Tel Aviv",
    "Mainz": "Mainz",
    "Malaga": "Malaga CF",
    "Malaga CF": "Malaga CF",
    "Mallorca": "Mallorca",
    "Malmo FF": "Malmo FF",
    "Malmö FF": "Malmo",
    "Man City": "Man City",
    "Man United": "Man Utd",
    "Man Utd": "Man Utd",
    "Manchester City U21": "Manchester City U21",
    "Mansfield Town": "Mansfield Town",
    "Mantova": "Mantova",
    "Maritimo": "Maritimo Madeira",
    "Maritimo Madeira": "Maritimo Madeira",
    "Marsaxlokk FC": "Marsaxlokk FC",
    "Marseille": "Marseille",
    "Mačva Šabac": "Macva Sabac",
    "Mechelen": "Yellow-Red KV Mechelen",
    "Metalist Kharkiv": "Metalist Kharkiv",
    "Metz": "Metz",
    "Middlesbrough": "Middlesbrough FC",
    "Middlesbrough FC": "Middlesbrough FC",
    "Midtjylland": "FC Midtjylland",
    "Millwall": "Millwall FC",
    "Milsami Orhei": "Milsami",
    "Mjallby": "Mjallby AIF",
    "Mjällby": "Mjallby AIF",
    "Mladost Lucani": "Mladost Lucani",
    "Mladost Lučani": "Mladost Lucani",
    "Molde": "Molde",
    "Monaco": "Monaco",
    "Mondorf-les-Bains": "US Mondorf-les-bains",
    "Montpellier": "Montpellier",
    "Monza": "Monza",
    "Moreirense FC": "Moreirense",
    "Mornar": "Mornar",
    "Mosta": "Mosta",
    "Motherwell": "Motherwell FC",
    "Mura Murska Sobota": "Mura Murska Sobota",
    "NK Brinje Grosuplje": "NK Brinje Grosuplje",
    "NK Istra 1961": "Istra 1961",
    "NK Lokomotiva Zagreb": "NK Lokomotiva Zagreb",
    "NK Maribor": "NK Maribor",
    "NK Osijek": "NK Osijek",
    "NK Radomlje": "NK Radomlje",
    "NK Rudes Zagreb": "NK Rudes Zagreb",
    "NK Slaven Belupo": "NK Slaven Belupo",
    "NK Varazdin": "NK Varazdin",
    "NSI Runavik": "NSI Runavik",
    "Nacional da Madeira": "Nacional da Madeira",
    "Nacional de Madeira": "Nacional",
    "Nafta 1903 Lendava": "Nafta 1903 Lendava",
    "Nancy-Lorraine": "Nancy-Lorraine",
    "Nantes": "Nantes",
    "Napoli": "Napoli",
    "Newcastle": "Newcastle",
    "Nice": "Nice",
    "Nijmegen": "NEC Nijmegen",
    "Noah": "FC Noah",
    "Nordsjaelland": "Nordsjaelland",
    "Norwich": "Norwich",
    "Nottingham Forest": "Nott'm Forest",
    "Nottm Forest": "Nottm Forest",
    "Nyiregyhaza Spartacus FC": "Nyiregyhaza Spartacus FC",
    "Nyíregyháza": "Nyiregyhaza",
    "OFI": "OFI",
    "OFI Crete": "OFI Crete",
    "OFK Beograd": "OFK Beograd",
    "Obolon Kyiv": "Obolon Kyiv",
    "Odds BK": "Odd",
    "Odense": "Odense Boldklub",
    "Ogre United": "Ogre United",
    "Olimpija Ljubljana": "Olimpija Ljubljana",
    "Olympiakos Piraeus": "Olympiacos",
    "Omonia Nicosia": "AC Omonia Nicosia",
    "Osasuna": "Osasuna",
    "Oud-Heverlee Leuven": "Oud-Heverlee Leuven",
    "Oțelul Galați": "Oţelul",
    "PAE PS Kalamata": "PAE PS Kalamata",
    "PAOK": "PAOK",
    "PFC CSKA Sofia": "PFC CSKA Sofia",
    "PFK Krylia Sovetov Samara": "PFK Krylia Sovetov Samara",
    "POT Iraklis": "POT Iraklis",
    "PSG": "Paris Saint-Germain",
    "PSV Eindhoven": "PSV Eindhoven",
    "Paderborn": "Paderborn",
    "Pafos FC": "Pafos",
    "Paksi FC": "Paksi FC",
    "Palermo FC": "Palermo FC",
    "Panaitolikos Agrinio": "Panaitolikos Agrinio",
    "Panathinaikos": "Panathinaikos",
    "Paris FC": "Paris FC",
    "Paris Saint-Germain": "Paris SG",
    "Parma": "Parma Calcio",
    "Parma Calcio": "Parma Calcio",
    "Partizan Belgrade": "FK Partizan",
    "Partizani Tirana": "Partizani",
    "Pau FC": "Pau FC",
    "Pen-y-Bont": "Penybont",
    "Pen-y-Bont FC": "Pen-y-Bont FC",
    "Peterborough United": "Peterborough United",
    "Petrocub": "Petrocub",
    "Petrocub Hincesti": "Petrocub Hincesti",
    "Petrocub Hîncești": "Petrocub",
    "Petrolul Ploiești": "Petrolul Ploiesti",
    "Petrovac": "Petrovac",
    "Piteaa IF DFF": "Piteaa IF DFF",
    "Plymouth Argyle": "Plymouth Argyle",
    "Podbrezová": "Podbrezová",
    "Pogon Szczecin": "Pogon Szczecin",
    "Polissya Zhytomyr": "Polissya Zhytomyr",
    "Politehnica UTM": "Politehnica UTM",
    "Portadown FC": "Portadown FC",
    "Porto": "FC Porto",
    "Portsmouth FC": "Portsmouth",
    "Preston": "Preston North End",
    "Preston North End": "Preston North End",
    "Progrès Niederkorn": "Progres Niederkorn",
    "Puskas Akademia FC Felcsut": "Puskas Akademia FC Felcsut",
    "Puskas Akademia Felcsut": "Puskas Akademia Felcsut",
    "Puskás Akadémia": "Puskas Academy",
    "Qarabag": "Qarabag",
    "Queens Park Rangers": "QPR",
    "RAAL La Louviere": "RAAL La Louviere",
    "RB Leipzig": "RB Leipzig",
    "RC Deportivo De La Coruna": "RC Deportivo De La Coruna",
    "RFK Akhmat Grozny": "RFK Akhmat Grozny",
    "RKS Radomiak Radom": "Radomiak Radom",
    "Racing Santander": "Racing Santander",
    "Racing Union Luxembourg": "Racing FC Union Luxembourg",
    "Radnicki 1923": "Radnicki 1923",
    "Radnicki NIS": "Radnicki NIS",
    "Radnički 1923": "Radnicki 1923",
    "Radnički Niš": "Radnicki NIS",
    "Rakow": "Rakow Czestochowa",
    "Randers FC": "Randers FC",
    "Rangers": "Rangers",
    "Rapid București": "Rapid Bucuresti",
    "Rayo Vallecano": "Vallecano",
    "Reading FC": "Reading FC",
    "Real Madrid": "Real Madrid",
    "Real Sireți": "Real Sireti",
    "Real Sociedad": "Sociedad",
    "Reims": "Reims",
    "Rennes": "Rennes",
    "Residence Walferdange": "Residence Walferdange",
    "Rigas FS": "Rigas FS",
    "Rio Ave": "Rio Ave FC",
    "Rio Ave FC": "Rio Ave FC",
    "Rizespor": "Caykur Rizespor",
    "Rodez": "Rodez",
    "Rodez Aveyron Football": "Rodez Aveyron Football",
    "Rodina Moscow": "Rodina Moscow",
    "Roma": "Roma",
    "Rosenborg BK": "Rosenborg",
    "Rot-Weiss Essen": "Rot-Weiss Essen",
    "Rubin Kazan": "Rubin",
    "Rumelange": "Rumelange",
    "Rīgas FS": "Riga FC",
    "SC Cambuur": "SC Cambuur",
    "SC Gjilani": "SC Gjilani",
    "SC Pisa": "SC Pisa",
    "SC Preussen 06 Munster": "SC Preussen 06 Munster",
    "SC St Tonis 11/20": "SC St Tonis 11/20",
    "SC Verl": "SC Verl",
    "SCR Altach": "Altach",
    "SG Sonnenhof Grossaspach": "SG Sonnenhof Grossaspach",
    "SK Brann": "SK Brann",
    "SK Dynamo České Budějovice": "Ceske Budejovice",
    "SK Rapid": "SK Rapid",
    "SK Sigma Olomouc": "Sigma Olomouc",
    "SK Super Nova": "SK Super Nova",
    "SSV Jeddeloh II": "SSV Jeddeloh II",
    "ST Johnstone": "St Johnstone",
    "SV 07 Elversberg": "SV 07 Elversberg",
    "SV Ried": "Ried",
    "SV Waldhof Mannheim 07": "SV Waldhof Mannheim 07",
    "SV Wehen Wiesbaden": "SV Wehen Wiesbaden",
    "SV Westfalia Rhynern": "SV Westfalia Rhynern",
    "S\xf8nderjyske": "Sonderjyske",
    "Sabah Baku": "Sabah Masazir",
    "Saint Etienne": "Saint-Etienne",
    "Saku Sporting": "Saku Sporting",
    "Salzburg": "Salzburg",
    "Sampdoria Genoa": "Sampdoria Genoa",
    "Samsunspor": "Samsunspor",
    "Sandefjord Fotball": "Sandefjord",
    "Santa Clara Azores": "Santa Clara Azores",
    "Sardarapat FC": "Sardarapat FC",
    "Sarpsborg 08": "Sarpsborg 08",
    "Sarpsborg 08 FF": "Sarpsborg",
    "Sassuolo": "Sassuolo",
    "Schalke": "Schalke",
    "Seinajoen JK": "Seinajoen JK",
    "Servette FC": "Servette",
    "Servette Geneva": "Servette Geneva",
    "Servette Geneva W": "Servette Geneva W",
    "Sevilla": "Sevilla",
    "Shakhtar": "Shakhtar Donetsk",
    "Shakhtar Donetsk": "Shakhtar Donetsk",
    "Shamrock Rovers": "Shamrock Rovers",
    "Sheffield United": "Sheffield United",
    "Sheffield Utd": "Sheffield United",
    "Sheffield Wednesday": "Sheffield Wednesday",
    "Sheriff Tiraspol": "Sheriff Tiraspol",
    "Shirak": "Shirak Gyumri",
    "Shrewsbury Town": "Shrewsbury Town",
    "Silkeborg": "Silkeborg IF",
    "Skala IF": "Skala IF",
    "Skënderbeu Korçë": "Skenderbeu Korce",
    "Slavia Prague": "Slavia Praha",
    "Sliema Wanderers": "Sliema Wanderers",
    "Slovan Bratislava": "Slovan Bratislava",
    "SonderjyskE": "Sonderjyske",
    "Southampton": "Southampton",
    "Sp Braga": "Braga",
    "Sp Lisbon": "Sporting CP",
    "Sparta Praha": "Sparta Prague",
    "Sparta Rotterdam": "Sparta Rotterdam",
    "Spartak Moscow": "Spartak Moscow",
    "Spartak Trnava": "Spartak Trnava",
    "Sporting": "Sporting",
    "St Johnstone": "St Johnstone",
    "St Mirren": "St Mirren FC",
    "St Truiden": "St. Truidense VV",
    "St. Gilloise": "Union Gilloise",
    "St. Johnstone FC": "St. Johnstone FC",
    "Stabæk Fotball": "Stabaek",
    "Stade Brestois 29": "Brest",
    "Stade Lavallois MFC": "Stade Lavallois MFC",
    "Standard": "Standard Liege",
    "Stevenage FC": "Stevenage FC",
    "Stoke": "Stoke City",
    "Stoke City": "Stoke City",
    "Strasbourg": "Strasbourg",
    "Sturm Graz": "SK Sturm Graz",
    "Stuttgart": "Stuttgart",
    "Sudtirol": "Sudtirol",
    "Sunderland": "Sunderland AFC",
    "Sunderland AFC": "Sunderland AFC",
    "Swansea": "Swansea City",
    "Swansea City": "Swansea City",
    "Swift Hesperange": "Swift Hesperange",
    "TSV 1860 Munich": "TSV 1860 Munich",
    "TSV Hartberg": "Hartberg",
    "TSV Schott Mainz": "TSV Schott Mainz",
    "Tallinna FC Flora": "Tallinna FC Flora",
    "Tampereen Ilves": "Tampereen Ilves",
    "Telstar": "SC Telstar",
    "The New Saints": "TNS",
    "The New Saints FC": "The New Saints FC",
    "Tobol Kostanay": "Tobol Kostanay",
    "Tofta Itrottarfelag B68": "Tofta Itrottarfelag B68",
    "Tottenham": "Tottenham",
    "Toulouse": "Toulouse",
    "Trabzonspor": "Trabzonspor",
    "Trefelin BGC": "Trefelin BGC",
    "Trenčín": "AS Trencin",
    "Tromsoe IL": "Tromsoe IL",
    "Tromsø IL": "Tromso",
    "Troyes": "Troyes",
    "Turun Palloseura": "Turun Palloseura",
    "Twente": "FC Twente Enschede",
    "UCSA Tarasivka": "UCSA",
    "UNA Strassen": "UNA Strassen",
    "US Boulogne": "US Boulogne",
    "US Cremonese": "US Cremonese",
    "US Lecce": "Lecce",
    "USL Dunkerque": "USL Dunkerque",
    "UTA Arad": "Uta Arad",
    "Udinese": "Udinese",
    "Ujpest FC Budapest": "Ujpest FC Budapest",
    "Ulytau FC": "Ulytau FC",
    "Union Berlin": "Union Berlin",
    "Urartu": "FC Urartu",
    "Utrecht": "FC Utrecht",
    "VFB 1921 Krieschow": "VFB 1921 Krieschow",
    "VSG Altglienicke": "VSG Altglienicke",
    "Vaalerenga IF": "Vaalerenga IF",
    "Vaasan Palloseura": "Vaasan Palloseura",
    "Valencia": "Valencia",
    "Valletta": "Valletta",
    "Vasas FC": "Vasas FC",
    "Vaxjo DFF": "Vaxjo DFF",
    "Venezia FC": "Venezia FC",
    "Veres Rivne": "Veres Rivne",
    "Verona": "Verona",
    "VfL 1899 Osnabruck": "VfL 1899 Osnabruck",
    "Viborg": "Viborg FF",
    "Victoria Rosport": "Victoria Rosport",
    "Viimsi JK": "Viimsi JK",
    "Viking FK": "Viking",
    "Vikingur Gota": "Vikingur Gota",
    "Vikingur Reykjavik": "Vikingur Reykjavik",
    "Viktoria Plzen": "Viktoria Plzen",
    "Villarreal": "Villarreal",
    "Virtus Entella": "Virtus Entella",
    "Vitoria SC Guimaraes": "Vitoria SC Guimaraes",
    "Vittsjo GIK": "Vittsjo GIK",
    "Vllaznia": "Vllaznia Shkodër",
    "Vllaznia Shkodër": "Vllaznia Shkodër",
    "Volos": "Volos NFC",
    "Volos NPS": "Volos NPS",
    "Västerås SK": "Vasteras",
    "WKS Slask Wroclaw": "WKS Slask Wroclaw",
    "WKW ETO FC Gyor": "WKW ETO FC Gyor",
    "WSG Tirol": "Tirol",
    "Walsall FC": "Walsall FC",
    "Waregem": "SV Zulte Waregem",
    "Watford": "Watford",
    "Werder Bremen": "Werder Bremen",
    "West Bromwich Albion": "West Brom",
    "West Ham": "West Ham",
    "Westerlo": "KVC Westerlo",
    "Widzew Lodz": "Widzew Lodz",
    "Wieczysta Krakow": "Wieczysta Krakow",
    "Willem II": "Willem II Tilburg",
    "Wiltz 71": "Wiltz",
    "Wisla Krakow": "Wisla Krakow",
    "Wisla Plock": "Wisla Plock",
    "Wolfsberger AC": "Wolfsberger AC",
    "Wolfsburg": "Wolfsburg",
    "Wolves": "Wolves",
    "Wrexham": "Wrexham AFC",
    "Wrexham AFC": "Wrexham AFC",
    "Yellow-Red KV Mechelen": "Yellow-Red KV Mechelen",
    "Young Boys Bern": "Young Boys Bern",
    "Yverdon Sport FC": "Yverdon",
    "Zabbar Saint Patrick FC": "Zabbar Saint Patrick FC",
    "Zabbar St. Patrick": "Zabbar St. Patrick",
    "Zaglebie": "Zaglebie Lubin",
    "Zalaegerszeg": "Zalaegerszegi TE",
    "Zalaegerszeg TE": "Zalaegerszeg TE",
    "Zemun": "Zemun",
    "Zenit Saint Petersburg": "Zenit St Petersburg",
    "Zhetysu Taldykorgan": "Zhetysu Taldykorgan",
    "Zimbru Chișinău": "Zimbru Chisinau",
    "Zorya Luhansk": "Zorya Luhansk",
    "Zwolle": "Zwolle",
    "de Graafschap": "de Graafschap",
    "Çorum": "Corum",
    "Újpest": "Ujpest",
    "Čukarički": "Cukaricki",
    "İstanbul Başakşehir": "Başakşehir",
    "Železiarne Podbrezová": "Podbrezová",    "BK Hacken": "BK Hacken",
    "Degerfors IF": "Degerfors IF",
    "Djurgardens IF": "Djurgardens IF",
    "Orgryte IS": "Orgryte IS",
    "Vasteraas SK": "Vasteraas SK",
    "Hapoel Be`er Sheva FC": "Hapoel Be`er Sheva FC",
    "PEC Zwolle": "PEC Zwolle",
    "BK Hacken": "BK Hacken",
    "Degerfors IF": "Degerfors IF",
    "Djurgardens IF": "Djurgardens IF",
    "Orgryte IS": "Orgryte IS",
    "Vasteraas SK": "Vasteraas SK",

}


# Reverse table: SportyBet league-page spelling -> OLP XDV model key. Built
# once from SPORTYBET_TEAMS (model key -> SportyBet name). First-wins on
# collisions preserves the canonical key — the table is ordered canonical-
# before-alias, e.g. "AZ Alkmaar" before "Alkmaar" (reverse("Alkmaar") ->
# "AZ Alkmaar") and "Sheffield Utd" before "Sheffield United" (reverse
# ("Sheffield United") -> "Sheffield Utd").
_MODEL_BY_SPORTYBET: dict[str, str] = {}
for _olp_key, _sb_name in SPORTYBET_TEAMS.items():
    _MODEL_BY_SPORTYBET.setdefault(_sb_name, _olp_key)


def _normalize(name: str) -> str:
    """Normalize a team name for comparison."""
    name = name.lower().strip()
    # Remove common prefixes/suffixes
    for prefix in ("fc ", "sc ", "ac ", "cd ", "cf ", "rk ", "ss "):
        if name.startswith(prefix):
            name = name[len(prefix):]
    for suffix in (" fc", " sc", " ac", " cf", " if", " bk", " fk", " sk"):
        if name.endswith(suffix):
            name = name[:-len(suffix)]
    # Remove diacritics (basic)
    replacements = {"á": "a", "é": "e", "í": "i", "ó": "o", "ú": "u",
                    "ä": "a", "ö": "o", "ü": "u", "ñ": "n", "ø": "o",
                    "æ": "ae", "ß": "ss"}
    for old, new in replacements.items():
        name = name.replace(old, new)
    return name.strip()


def resolve_team(olp_name: str, bookmaker: str = "sportybet") -> str:
    """Resolve an OLP XDV team name to a bookmaker's official name.

    Strategy:
    1. Exact match in SPORTYBET_TEAMS / BET365_TEAMS dict
    2. Fuzzy match using normalized names and SequenceMatcher
    3. Return original name if no match found (best effort)

    Returns the bookmaker's official name, or the original OLP name as fallback.
    """
    # 1. Exact match
    if bookmaker == "sportybet":
        if olp_name in SPORTYBET_TEAMS:
            return SPORTYBET_TEAMS[olp_name]
    # (Bet365 teams TBD)

    # 2. Fuzzy match
    target = _normalize(olp_name)
    best_match = None
    best_score = 0.0

    from difflib import SequenceMatcher
    source = SPORTYBET_TEAMS if bookmaker == "sportybet" else {}
    for olp_key, bm_name in source.items():
        bm_norm = _normalize(bm_name)
        # Prefix match (one contains the other)
        if target in bm_norm or bm_norm in target:
            score = 0.9
        else:
            score = SequenceMatcher(None, target, bm_norm).ratio()
        if score > best_score:
            best_score = score
            best_match = bm_name

    if best_score >= 0.6:
        return best_match

    # 3. Fallback: return original
    return olp_name


def resolve_team_to_model(sportybet_name: str) -> str:
    """SportyBet league-page name -> OLP XDV model key (football-data short name).

    The REVERSE of resolve_team, used by the SportyBet cache builder so
    model_home/model_away hold REAL model keys, not SportyBet spellings. The
    old code called resolve_team backwards (SportyBet name -> table of
    SportyBet VALUES), which fuzzy-matched one club against another and could
    return a DIFFERENT team entirely — e.g. "Millwall FC" -> "AC Milan",
    "Club Brugge" -> "Cercle Brugge", "Excelsior Rotterdam" ->
    "Sparta Rotterdam". That attached one club's real price to the wrong model
    team.

    EXACT + NORMALIZED-EXACT ONLY — deliberately NO fuzzy pass (HR35). A name
    that isn't in the reverse table returns UNCHANGED so the caller reports
    NO DATA — PENDING. Attaching a real price to the wrong team is worse than
    an honest gap, so we never guess across clubs.
    """
    if sportybet_name in _MODEL_BY_SPORTYBET:
        return _MODEL_BY_SPORTYBET[sportybet_name]
    target = _normalize(sportybet_name)
    for sb_name, model_key in _MODEL_BY_SPORTYBET.items():
        if _normalize(sb_name) == target:
            return model_key
    return sportybet_name
