SPORTYBET_TEAMS: dict[str, str] = {
    "07 Vestur Sorvagur": "07 Vestur Sorvagur",
    "1 FC Kaiserslautern": "1 FC Kaiserslautern",
    "1 FC Nuremberg": "1 FC Nuremberg",
    "1. FC Magdeburg": "1. FC Magdeburg",
    "1. FC Phonix Lubeck": "1. FC Phonix Lubeck",
    "1. FC Saarbrucken": "1. FC Saarbrucken",
    "AB Argir": "AB Argir",
    "AC Horsens": "AC Horsens",
    "AC Milan": "AC Milan",
    "AC Oulu": "AC Oulu",
    "ADO Den Haag": "ADO Den Haag",
    "AEK Athens": "AEK Athens",
    "AFC Wimbledon": "AFC Wimbledon",
    "AGF Aarhus": "AGF Aarhus",
    "AIK DFF": "AIK DFF",
    "APO Levadiakos FC": "APO Levadiakos FC",
    "AZ Alkmaar": "Alkmaar",
    "Aalesunds FK": "Aalesunds FK",
    "Aarhus": "AGF Aarhus",
    "Aberdeen": "Aberdeen",
    "Academico de Viseu FC": "Academico de Viseu FC",
    "Airbus UK Broughton": "Airbus UK Broughton",
    "Ajax": "Ajax",
    "Alanyaspor": "Alanyaspor",
    "Alashkert": "FC Alashkert",
    "Alaves": "Alaves",
    "Alkmaar": "Alkmaar",
    "Aluminij Kidricevo": "Aluminij Kidricevo",
    "Alverca Futebol": "Alverca Futebol",
    "Amed Sportif Faaliyetler": "Amed Sportif Faaliyetler",
    "Ammanford": "Ammanford",
    "Anderlecht": "RSC Anderlecht",
    "Angers": "Angers",
    "Antwerp": "Royal Antwerp FC",
    "Apollon Limassol": "Apollon Limassol",
    "Ararat": "Ararat Yerevan",
    "Ararat-Armenia": "FC Ararat-Armenia",
    "Aris Thessaloniki": "Aris Thessaloniki",
    "Arminia Bielefeld": "Arminia Bielefeld",
    "Arsenal": "Arsenal",
    "Astana": "Astana",
    "Asteras Tripolis": "Asteras Tripolis",
    "Aston Villa": "Aston Villa",
    "Atalanta": "Atalanta",
    "Ath Madrid": "Atletico Madrid",
    "Athletic Bilbao": "Athletic Bilbao",
    "Atletico Madrid": "Atletico Madrid",
    "Atromitos Athinon": "Atromitos Athinon",
    "Augsburg": "Augsburg",
    "Austria Lustenau": "Austria Lustenau",
    "Auxerre": "AJ Auxerre",
    "B36 Torshavn": "B36 Torshavn",
    "BFC Daugavpils": "BFC Daugavpils",
    "Bahlinger SC": "Bahlinger SC",
    "Ballymena United": "Ballymena United",
    "Balzan": "Balzan FC",
    "Bangor FC": "Bangor FC",
    "Barcelona": "Barcelona",
    "Barnsley FC": "Barnsley FC",
    "Barry Town United FC": "Barry Town United FC",
    "Bayer Leverkusen": "Bayer Leverkusen",
    "Bayern Munich": "Bayern Munich",
    "Benfica": "Benfica",
    "Besiktas Istanbul": "Besiktas Istanbul",
    "Betis": "Real Betis",
    "Beveren": "KV Waasland-Beveren",
    "Birkirkara": "Birkirkara",
    "Birmingham City": "Birmingham City",
    "Birzebbuga St. Peter": "Birzebbuga St. Peter",
    "Blackburn Rovers": "Blackburn Rovers",
    "Blackpool FC": "Blackpool FC",
    "Bnei Sakhnin FC": "Bnei Sakhnin FC",
    "Bochum": "Bochum",
    "Bodo/Glimt": "Bodoe/Glimt",
    "Bodoe/Glimt": "Bodoe/Glimt",
    "Bologna": "Bologna",
    "Bolton Wanderers": "Bolton Wanderers",
    "Borac Banja Luka": "FK Borac Banja Luka",
    "Borussia M´gladbach": "Borussia M´gladbach",
    "Bournemouth": "Bournemouth",
    "Bradford City FC": "Bradford City FC",
    "Braga": "SC Braga",
    "Bravo Ljubljana": "Bravo Ljubljana",
    "Brentford": "Brentford",
    "Brest": "Brest",
    "Brighton": "Brighton",
    "Bristol City": "Bristol City",
    "Briton Ferry": "Briton Ferry",
    "Brondby": "Broendby IF",
    "Burnley": "Burnley",
    "CSKA Moscow": "CSKA Moscow",
    "Caernarfon Town FC": "Caernarfon Town FC",
    "Cagliari": "Cagliari",
    "Cambrian United": "Cambrian United",
    "Cambridge United": "Cambridge United",
    "Cardiff City": "Cardiff City",
    "Cardiff Metropolitan University FC": "Cardiff Metropolitan University FC",
    "Carrick Rangers": "Carrick Rangers",
    "Casa Pia Lisbon": "Casa Pia Lisbon",
    "Caykur Rizespor": "Caykur Rizespor",
    "Celje": "NK Celje",
    "Celta": "Celta",
    "Celtic": "Celtic",
    "Cercle Brugge": "Cercle Brugge",
    "Cesena FC": "Cesena FC",
    "Charleroi": "Royal Charleroi SC",
    "Charlton Athletic": "Charlton Athletic",
    "Chelsea": "Chelsea",
    "Cliftonville FC": "Cliftonville FC",
    "Club Brugge": "Club Brugge",
    "Coleraine FC": "Coleraine FC",
    "Cologne": "Cologne",
    "Colwyn Bay": "Colwyn Bay",
    "Como 1907": "Como 1907",
    "Connah`s Quay Nomads FC": "Connah`s Quay Nomads FC",
    "Copenhagen": "Copenhagen",
    "Corum FK": "Corum FK",
    "Coventry City": "Coventry City",
    "Crewe Alexandra": "Crewe Alexandra",
    "Crusaders FC": "Crusaders FC",
    "Crystal Palace": "Crystal Palace",
    "Darmstadt": "Darmstadt",
    "Debreceni VSC": "Debreceni VSC",
    "Derby County": "Derby County",
    "Dinamo Zagreb": "GNK Dinamo Zagreb",
    "Djurgardens IF DFF": "Djurgardens IF DFF",
    "Doncaster Rovers": "Doncaster Rovers",
    "Dortmund": "Borussia Dortmund",
    "Dundee United": "Dundee United",
    "Dundee": "Dundee",
    "Dungannon Swifts": "Dungannon Swifts",
    "Dynamo Dresden": "Dynamo Dresden",
    "Eb/Streymur": "Eb/Streymur",
    "Egnatia": "KF Egnatia Rrogozhine",
    "Eintracht Braunschweig": "Eintracht Braunschweig",
    "Eintracht Frankfurt": "Eintracht Frankfurt",
    "Eintracht Trier": "Eintracht Trier",
    "Elche CF": "Elche CF",
    "Elche": "Elche CF",
    "Empoli": "Empoli",
    "Energie Cottbus": "Energie Cottbus",
    "Erzgebirge Aue": "Erzgebirge Aue",
    "Erzurumspor FK": "Erzurumspor FK",
    "Eskilstuna United DFF": "Eskilstuna United DFF",
    "Espanyol": "Espanyol",
    "Estoril Praia": "Estoril Praia",
    "Everton": "Everton",
    "Excelsior": "Excelsior Rotterdam",
    "Exeter City": "Exeter City",
    "Eyupspor": "Eyupspor",
    "FC Aktobe": "FC Aktobe",
    "FC Alashkert Yerevan": "FC Alashkert Yerevan",
    "FC Altai Oskemen": "FC Altai Oskemen",
    "FC Arouca": "FC Arouca",
    "FC Baltika Kaliningrad": "FC Baltika Kaliningrad",
    "FC CSKA 1948": "FC CSKA 1948",
    "FC Carl Zeiss Jena": "FC Carl Zeiss Jena",
    "FC Dila Gori": "FC Dila Gori",
    "FC Dinamo Batumi": "FC Dinamo Batumi",
    "FC Dinamo City": "FC Dinamo City",
    "FC Dynamo-Makhachkala": "FC Dynamo-Makhachkala",
    "FC Fakel Voronezh": "FC Fakel Voronezh",
    "FC Famalicao": "FC Famalicao",
    "FC Hradec Kralove": "FC Hradec Kralove",
    "FC Inter Turku": "FC Inter Turku",
    "FC Irtysh Pavlodar": "FC Irtysh Pavlodar",
    "FC Koper": "FC Koper",
    "FC Lahti": "FC Lahti",
    "FC Meshakhte Tkibuli": "FC Meshakhte Tkibuli",
    "FC Milsami": "FC Milsami",
    "FC Ordabasy": "FC Ordabasy",
    "FC Orenburg": "FC Orenburg",
    "FC Pyunik Yerevan": "FC Pyunik Yerevan",
    "FC RFS": "FC RFS",
    "FC Real Sireti": "FC Real Sireti",
    "FC Rosengaard Malmo": "FC Rosengaard Malmo",
    "FC ST. Gallen": "FC St. Gallen 1879",
    "FC St. Gallen": "FC St. Gallen 1879",
    "FC St. Pauli": "FC St. Pauli",
    "FC Torino": "FC Torino",
    "FC Torpedo Kutaisi": "FC Torpedo Kutaisi",
    "FC Urartu Yerevan": "FC Urartu Yerevan",
    "FC Viktoria Cologne": "FC Viktoria Cologne",
    "FC Wurzburger Kickers": "FC Wurzburger Kickers",
    "FC Yelimai": "FC Yelimai",
    "FC Zhenis": "FC Zhenis",
    "FC Zimbru Chisinau": "FC Zimbru Chisinau",
    "FF Jaro": "FF Jaro",
    "FK Akron Tolyatti": "FK Akron Tolyatti",
    "FK Atyrau": "FK Atyrau",
    "FK Auda Riga": "FK Auda Riga",
    "FK Austria Wien": "FK Austria Wien",
    "FK Crvena Zvezda": "Crvena Zvezda",
    "FK Dinamo Moscow": "FK Dinamo Moscow",
    "FK Jablonec": "FK Jablonec",
    "FK Kaspii Aktau": "FK Kaspii Aktau",
    "FK Krasnodar": "FK Krasnodar",
    "FK Liepaja": "FK Liepaja",
    "FK Rostov": "FK Rostov",
    "FK Rubin Kazan": "FK Rubin Kazan",
    "FK Spartak Moscow": "FK Spartak Moscow",
    "FK Tukums 2000/TSS": "FK Tukums 2000/TSS",
    "FK Zenit Saint Petersburg": "FK Zenit Saint Petersburg",
    "FS Jelgava": "FS Jelgava",
    "Falkirk": "Falkirk FC",
    "Fenerbahce": "Fenerbahce Istanbul",
    "Fenerbahçe": "Fenerbahce Istanbul",
    "Feyenoord": "Feyenoord",
    "Fiorentina": "Fiorentina",
    "Fleetwood Town": "Fleetwood Town",
    "Flint Town United": "Flint Town United",
    "Floriana": "Floriana",
    "For Sittard": "Fortuna Sittard",
    "Fortuna D": "Fortuna D",
    "Fredrikstad FK": "Fredrikstad FK",
    "Freiburg": "Freiburg",
    "Frosinone": "Frosinone",
    "Fulham": "Fulham",
    "GKS Katowice": "GKS Katowice",
    "GKS Piast Gliwice": "GKS Piast Gliwice",
    "Galatasaray Istanbul": "Galatasaray Istanbul",
    "Gandzasar Kapan FC": "Gandzasar Kapan FC",
    "Gaziantep FK": "Gaziantep FK",
    "Genclerbirligi SK": "Genclerbirligi SK",
    "Genk": "Genk",
    "Genoa": "Genoa",
    "Gent": "Gent",
    "Getafe": "Getafe",
    "Gil Vicente Barcelos": "Gil Vicente Barcelos",
    "Girona": "Girona",
    "Glentoran FC": "Glentoran FC",
    "Go Ahead Eagles": "Go Ahead Eagles",
    "Goztepe Izmir": "Goztepe Izmir",
    "Grazer AK 1902": "Grazer AK 1902",
    "Greuther Furth": "Greuther Furth",
    "Grobinas SC/LFS": "Grobinas SC/LFS",
    "Groningen": "FC Groningen",
    "Guimaraes": "Vitoria de Guimaraes",
    "Gzira United": "Gzira United",
    "HB Torshavn": "HB Torshavn",
    "HJK Helsinki": "HJK Helsinki",
    "HNK Gorica": "HNK Gorica",
    "HNK Hajduk Split": "HNK Hajduk Split",
    "HNK Rijeka": "HNK Rijeka",
    "Hacken Gothenburg W": "Hacken Gothenburg W",
    "Hallescher FC": "Hallescher FC",
    "HamKam": "HamKam",
    "Hamburger SV": "Hamburger SV",
    "Hammarby IF": "Hammarby IF",
    "Hamrun Spartans": "Hamrun Spartans",
    "Hansa Rostock": "Hansa Rostock",
    "Hapoel Be'er Sheva": "Hapoel Be`er Sheva FC",
    "Hapoel Jerusalem FC": "Hapoel Jerusalem FC",
    "Hapoel Petah Tikva FC": "Hapoel Petah Tikva FC",
    "Harju JK Laagri": "Harju JK Laagri",
    "Haverfordwest County AFC": "Haverfordwest County AFC",
    "Hearts": "Heart of Midlothian FC",
    "Heerenveen": "SC Heerenveen",
    "Heidenheim": "Heidenheim",
    "Hertha": "Hertha",
    "Hibernian": "Hibernian FC",
    "Hibernians FC Paola": "Hibernians FC Paola",
    "Hoffenheim": "Hoffenheim",
    "Holstein Kiel": "Holstein Kiel",
    "Holywell Town": "Holywell Town",
    "Hull City": "Hull City",
    "IF Brommapojkarna": "IF Brommapojkarna",
    "IF Gnistan": "IF Gnistan",
    "IFK Mariehamn": "IFK Mariehamn",
    "IFK Norrkoping DFK": "IFK Norrkoping DFK",
    "IK Start": "IK Start",
    "IK Uppsala Fotboll": "IK Uppsala Fotboll",
    "Iberia 1999": "FC Iberia 1999",
    "Inter": "Inter Milan",
    "Ipswich Town": "Ipswich Town",
    "Ironi Tiberias": "Ironi Tiberias",
    "Istanbul BB": "Istanbul BB",
    "Jagiellonia": "Jagiellonia Bialystok",
    "Juventus": "Juventus",
    "KF Drenica Skenderaj": "KF Drenica Skenderaj",
    "KF Malisheva": "KF Malisheva",
    "KFUM Oslo": "KFUM Oslo",
    "KI Klaksvik": "KI Klaksvik",
    "KS Cracovia Krakow": "KS Cracovia Krakow",
    "Kairat Almaty": "FC Kairat Almaty",
    "Kaisar Kyzylorda": "Kaisar Kyzylorda",
    "Karlsruher SC": "Karlsruher SC",
    "Kasimpasa Istanbul": "Kasimpasa Istanbul",
    "Kauno Zalgiris": "FK Kauno Zalgiris",
    "Kauno Žalgiris": "FK Kauno Zalgiris",
    "Kilmarnock": "Kilmarnock FC",
    "Kisvarda FC": "Kisvarda FC",
    "Kocaelispor": "Kocaelispor",
    "Konyaspor": "Konyaspor",
    "Korona Kielce": "Korona Kielce",
    "Kortrijk": "KV Kortrijk",
    "Kristianstads DFF": "Kristianstads DFF",
    "Kristiansund BK": "Kristiansund BK",
    "Kuopion Palloseura": "Kuopion Palloseura",
    "LASK Linz": "LASK Linz",
    "LKP Motor Lublin": "LKP Motor Lublin",
    "Larne": "Larne FC",
    "Las Palmas": "Las Palmas",
    "Lask Linz": "LASK Linz",
    "Lazio": "Lazio",
    "Le Havre": "Le Havre",
    "Le Mans FC": "Le Mans FC",
    "Leeds United": "Leeds United",
    "Leganes": "Leganes",
    "Legia": "Legia Warszawa",
    "Leicester": "Leicester",
    "Lens": "RC Lens",
    "Levante": "Levante",
    "Levski Sofia": "PFC Levski Sofia",
    "Leyton Orient London": "Leyton Orient London",
    "Lille": "Lille",
    "Lillestroem": "Lillestroem SK",
    "Lillestrom": "Lillestroem SK",
    "Lillestrøm": "Lillestroem SK",
    "Limavady United FC": "Limavady United FC",
    "Lincoln City": "Lincoln City",
    "Linfield FC": "Linfield FC",
    "Linz": "LASK Linz",
    "Liverpool": "Liverpool",
    "Llandudno FC": "Llandudno FC",
    "Lokomotiv Moscow": "Lokomotiv Moscow",
    "Lommel": "Lommel SK",
    "Lorient": "Lorient",
    "Luneburger SK Hansa": "Luneburger SK Hansa",
    "Luton": "Luton",
    "Lyngby": "Lyngby BK",
    "Lyon": "Lyon",
    "MSV Duisburg": "MSV Duisburg",
    "MTK Budapest": "MTK Budapest",
    "Maccabi Netanya FC": "Maccabi Netanya FC",
    "Maccabi Tel Aviv FC": "Maccabi Tel Aviv FC",
    "Mainz": "Mainz",
    "Malaga CF": "Malaga CF",
    "Malaga": "Malaga CF",
    "Mallorca": "Mallorca",
    "Malmo FF": "Malmo FF",
    "Man City": "Man City",
    "Man Utd": "Man Utd",
    "Manchester City U21": "Manchester City U21",
    "Mansfield Town": "Mansfield Town",
    "Maritimo Madeira": "Maritimo Madeira",
    "Marsaxlokk FC": "Marsaxlokk FC",
    "Marseille": "Marseille",
    "Mechelen": "Yellow-Red KV Mechelen",
    "Middlesbrough FC": "Middlesbrough FC",
    "Midtjylland": "FC Midtjylland",
    "Millwall": "Millwall FC",
    "Mjallby": "Mjallby AIF",
    "Mjällby": "Mjallby AIF",
    "Molde": "Molde",
    "Monaco": "Monaco",
    "Montpellier": "Montpellier",
    "Monza": "Monza",
    "Mosta": "Mosta",
    "Motherwell": "Motherwell FC",
    "Mura Murska Sobota": "Mura Murska Sobota",
    "NK Brinje Grosuplje": "NK Brinje Grosuplje",
    "NK Istra 1961": "NK Istra 1961",
    "NK Lokomotiva Zagreb": "NK Lokomotiva Zagreb",
    "NK Maribor": "NK Maribor",
    "NK Osijek": "NK Osijek",
    "NK Rudes Zagreb": "NK Rudes Zagreb",
    "NK Slaven Belupo": "NK Slaven Belupo",
    "NK Varazdin": "NK Varazdin",
    "NSI Runavik": "NSI Runavik",
    "Nacional da Madeira": "Nacional da Madeira",
    "Nafta 1903 Lendava": "Nafta 1903 Lendava",
    "Nantes": "Nantes",
    "Napoli": "Napoli",
    "Newcastle": "Newcastle",
    "Nice": "Nice",
    "Nijmegen": "NEC Nijmegen",
    "Noah": "FC Noah",
    "Nordsjaelland": "Nordsjaelland",
    "Norwich": "Norwich",
    "Nottingham Forest": "Nottingham Forest",
    "Nottm Forest": "Nottm Forest",
    "Nyiregyhaza Spartacus FC": "Nyiregyhaza Spartacus FC",
    "OFI Crete": "OFI Crete",
    "Odense": "Odense Boldklub",
    "Ogre United": "Ogre United",
    "Olimpija Ljubljana": "Olimpija Ljubljana",
    "Olympiakos Piraeus": "Olympiacos",
    "Omonia Nicosia": "AC Omonia Nicosia",
    "Osasuna": "Osasuna",
    "Oud-Heverlee Leuven": "Oud-Heverlee Leuven",
    "PAE PS Kalamata": "PAE PS Kalamata",
    "PAOK": "PAOK",
    "PFC CSKA Sofia": "PFC CSKA Sofia",
    "PFK Krylia Sovetov Samara": "PFK Krylia Sovetov Samara",
    "POT Iraklis": "POT Iraklis",
    "PSG": "Paris Saint-Germain",
    "PSV Eindhoven": "PSV Eindhoven",
    "Paderborn": "Paderborn",
    "Pafos FC": "Pafos FC",
    "Paksi FC": "Paksi FC",
    "Palermo FC": "Palermo FC",
    "Panaitolikos Agrinio": "Panaitolikos Agrinio",
    "Panathinaikos": "Panathinaikos",
    "Paris FC": "Paris FC",
    "Parma Calcio": "Parma Calcio",
    "Pen-y-Bont FC": "Pen-y-Bont FC",
    "Peterborough United": "Peterborough United",
    "Piteaa IF DFF": "Piteaa IF DFF",
    "Plymouth Argyle": "Plymouth Argyle",
    "Pogon Szczecin": "Pogon Szczecin",
    "Portadown FC": "Portadown FC",
    "Porto": "FC Porto",
    "Portsmouth FC": "Portsmouth FC",
    "Preston North End": "Preston North End",
    "Puskas Akademia FC Felcsut": "Puskas Akademia FC Felcsut",
    "Queens Park Rangers": "Queens Park Rangers",
    "RAAL La Louviere": "RAAL La Louviere",
    "RB Leipzig": "RB Leipzig",
    "RC Deportivo De La Coruna": "RC Deportivo De La Coruna",
    "RFK Akhmat Grozny": "RFK Akhmat Grozny",
    "RKS Radomiak Radom": "RKS Radomiak Radom",
    "Racing Santander": "Racing Santander",
    "Rakow": "Rakow Czestochowa",
    "Randers FC": "Randers FC",
    "Rangers": "Rangers",
    "Rayo Vallecano": "Rayo Vallecano",
    "Reading FC": "Reading FC",
    "Real Madrid": "Real Madrid",
    "Real Sociedad": "Real Sociedad",
    "Reims": "Reims",
    "Rennes": "Rennes",
    "Rigas FS": "Rigas FS",
    "Rio Ave FC": "Rio Ave FC",
    "Rodina Moscow": "Rodina Moscow",
    "Roma": "Roma",
    "Rosenborg BK": "Rosenborg BK",
    "Rot-Weiss Essen": "Rot-Weiss Essen",
    "Rīgas FS": "Riga FC",
    "SC Cambuur": "SC Cambuur",
    "SC Pisa": "SC Pisa",
    "SC Preussen 06 Munster": "SC Preussen 06 Munster",
    "SC St Tonis 11/20": "SC St Tonis 11/20",
    "SC Verl": "SC Verl",
    "SCR Altach": "SCR Altach",
    "SG Sonnenhof Grossaspach": "SG Sonnenhof Grossaspach",
    "SK Brann": "SK Brann",
    "SK Super Nova": "SK Super Nova",
    "SSV Jeddeloh II": "SSV Jeddeloh II",
    "SV 07 Elversberg": "SV 07 Elversberg",
    "SV Ried": "SV Ried",
    "SV Waldhof Mannheim 07": "SV Waldhof Mannheim 07",
    "SV Wehen Wiesbaden": "SV Wehen Wiesbaden",
    "SV Westfalia Rhynern": "SV Westfalia Rhynern",
    "Sabah Baku": "Sabah Masazir",
    "Saint Etienne": "Saint-Etienne",
    "Saku Sporting": "Saku Sporting",
    "Sampdoria Genoa": "Sampdoria Genoa",
    "Samsunspor": "Samsunspor",
    "Sandefjord Fotball": "Sandefjord Fotball",
    "Santa Clara Azores": "Santa Clara Azores",
    "Sardarapat FC": "Sardarapat FC",
    "Sarpsborg 08": "Sarpsborg 08",
    "Sassuolo": "Sassuolo",
    "Schalke": "Schalke",
    "Seinajoen JK": "Seinajoen JK",
    "Servette Geneva W": "Servette Geneva W",
    "Sevilla": "Sevilla",
    "Sheffield United": "Sheffield United",
    "Sheffield Utd": "Sheffield United",
    "Sheffield Wednesday": "Sheffield Wednesday",
    "Sheriff Tiraspol": "Sheriff Tiraspol",
    "Shirak": "Shirak Gyumri",
    "Shrewsbury Town": "Shrewsbury Town",
    "Silkeborg": "Silkeborg IF",
    "Skala IF": "Skala IF",
    "Sliema Wanderers": "Sliema Wanderers",
    "Slovan Bratislava": "Slovan Bratislava",
    "SonderjyskE": "SonderjyskE",
    "Southampton": "Southampton",
    "Sp Braga": "Braga",
    "Sp Lisbon": "Sporting CP",
    "Sparta Praha": "Sparta Prague",
    "Sparta Rotterdam": "Sparta Rotterdam",
    "Sporting": "Sporting",
    "St Johnstone": "St Johnstone",
    "St Mirren": "St Mirren FC",
    "St Truiden": "St. Truidense VV",
    "St. Gilloise": "Union Gilloise",
    "Standard": "Standard Liege",
    "Stevenage FC": "Stevenage FC",
    "Stoke City": "Stoke City",
    "Strasbourg": "Strasbourg",
    "Sturm Graz": "SK Sturm Graz",
    "Stuttgart": "Stuttgart",
    "Sunderland AFC": "Sunderland AFC",
    "Swansea City": "Swansea City",
    "TSV 1860 Munich": "TSV 1860 Munich",
    "TSV Hartberg": "TSV Hartberg",
    "TSV Schott Mainz": "TSV Schott Mainz",
    "Tallinna FC Flora": "Tallinna FC Flora",
    "Tampereen Ilves": "Tampereen Ilves",
    "Telstar": "SC Telstar",
    "The New Saints FC": "The New Saints FC",
    "Tobol Kostanay": "Tobol Kostanay",
    "Tofta Itrottarfelag B68": "Tofta Itrottarfelag B68",
    "Tottenham": "Tottenham",
    "Toulouse": "Toulouse",
    "Trabzonspor": "Trabzonspor",
    "Trefelin BGC": "Trefelin BGC",
    "Tromsoe IL": "Tromsoe IL",
    "Troyes": "Troyes",
    "Turun Palloseura": "Turun Palloseura",
    "Twente": "FC Twente Enschede",
    "US Cremonese": "US Cremonese",
    "US Lecce": "US Lecce",
    "Udinese": "Udinese",
    "Ujpest FC Budapest": "Ujpest FC Budapest",
    "Ulytau FC": "Ulytau FC",
    "Union Berlin": "Union Berlin",
    "Urartu": "FC Urartu",
    "Utrecht": "FC Utrecht",
    "VFB 1921 Krieschow": "VFB 1921 Krieschow",
    "VSG Altglienicke": "VSG Altglienicke",
    "Vaalerenga IF": "Vaalerenga IF",
    "Vaasan Palloseura": "Vaasan Palloseura",
    "Valencia": "Valencia",
    "Valletta": "Valletta",
    "Vasas FC": "Vasas FC",
    "Vaxjo DFF": "Vaxjo DFF",
    "Venezia FC": "Venezia FC",
    "VfL 1899 Osnabruck": "VfL 1899 Osnabruck",
    "Viborg": "Viborg FF",
    "Viimsi JK": "Viimsi JK",
    "Viking FK": "Viking FK",
    "Vikingur Gota": "Vikingur Gota",
    "Vikingur Reykjavik": "Vikingur Reykjavik",
    "Viktoria Plzen": "Viktoria Plzen",
    "Villarreal": "Villarreal",
    "Vitoria SC Guimaraes": "Vitoria SC Guimaraes",
    "Vittsjo GIK": "Vittsjo GIK",
    "Volos NPS": "Volos NPS",
    "WKS Slask Wroclaw": "WKS Slask Wroclaw",
    "WKW ETO FC Gyor": "WKW ETO FC Gyor",
    "Walsall FC": "Walsall FC",
    "Waregem": "SV Zulte Waregem",
    "Watford": "Watford",
    "Werder Bremen": "Werder Bremen",
    "West Bromwich Albion": "West Bromwich Albion",
    "West Ham": "West Ham",
    "Westerlo": "KVC Westerlo",
    "Widzew Lodz": "Widzew Lodz",
    "Wieczysta Krakow": "Wieczysta Krakow",
    "Willem II": "Willem II Tilburg",
    "Wisla Krakow": "Wisla Krakow",
    "Wisla Plock": "Wisla Plock",
    "Wolfsburg": "Wolfsburg",
    "Wolves": "Wolves",
    "Wrexham AFC": "Wrexham AFC",
    "Young Boys Bern": "Young Boys Bern",
    "Zabbar St. Patrick": "Zabbar St. Patrick",
    "Zaglebie": "Zaglebie Lubin",
    "Zalaegerszeg TE": "Zalaegerszeg TE",
    "Zhetysu Taldykorgan": "Zhetysu Taldykorgan",
    "Zwolle": "PEC Zwolle",
}


# Reverse table: SportyBet league-page spelling -> OLP XDV model key. Built
# once from SPORTYBET_TEAMS (model key -> SportyBet name). First-wins on
# collisions preserves the canonical key — the table is ordered canonical-
# before-alias, e.g. "AZ Alkmaar" before "Alkmaar" (reverse("Alkmaar") ->
# "AZ Alkmaar") and "Sheffield Utd" before "Sheffield United" (reverse
# ("Sheffield United") -> "Sheffield Utd").
_MODEL_BY_SPORTYBET: dict[str, str] = {}
for _olp_key, _sb_name in SPORTYBET_TEAMS.items():
    _MODEL_BY_SPORTYBET.setdefault(_sb_name, _olp_key)


def _normalize(name: str) -> str:
    """Normalize a team name for comparison."""
    name = name.lower().strip()
    # Remove common prefixes/suffixes
    for prefix in ("fc ", "sc ", "ac ", "cd ", "cf ", "rk ", "ss "):
        if name.startswith(prefix):
            name = name[len(prefix):]
    for suffix in (" fc", " sc", " ac", " cf", " if", " bk", " fk", " sk"):
        if name.endswith(suffix):
            name = name[:-len(suffix)]
    # Remove diacritics (basic)
    replacements = {"á": "a", "é": "e", "í": "i", "ó": "o", "ú": "u",
                    "ä": "a", "ö": "o", "ü": "u", "ñ": "n", "ø": "o",
                    "æ": "ae", "ß": "ss"}
    for old, new in replacements.items():
        name = name.replace(old, new)
    return name.strip()


def resolve_team(olp_name: str, bookmaker: str = "sportybet") -> str:
    """Resolve an OLP XDV team name to a bookmaker's official name.

    Strategy:
    1. Exact match in SPORTYBET_TEAMS / BET365_TEAMS dict
    2. Fuzzy match using normalized names and SequenceMatcher
    3. Return original name if no match found (best effort)

    Returns the bookmaker's official name, or the original OLP name as fallback.
    """
    # 1. Exact match
    if bookmaker == "sportybet":
        if olp_name in SPORTYBET_TEAMS:
            return SPORTYBET_TEAMS[olp_name]
    # (Bet365 teams TBD)

    # 2. Fuzzy match
    target = _normalize(olp_name)
    best_match = None
    best_score = 0.0

    from difflib import SequenceMatcher
    source = SPORTYBET_TEAMS if bookmaker == "sportybet" else {}
    for olp_key, bm_name in source.items():
        bm_norm = _normalize(bm_name)
        # Prefix match (one contains the other)
        if target in bm_norm or bm_norm in target:
            score = 0.9
        else:
            score = SequenceMatcher(None, target, bm_norm).ratio()
        if score > best_score:
            best_score = score
            best_match = bm_name

    if best_score >= 0.6:
        return best_match

    # 3. Fallback: return original
    return olp_name


def resolve_team_to_model(sportybet_name: str) -> str:
    """SportyBet league-page name -> OLP XDV model key (football-data short name).

    The REVERSE of resolve_team, used by the SportyBet cache builder so
    model_home/model_away hold REAL model keys, not SportyBet spellings. The
    old code called resolve_team backwards (SportyBet name -> table of
    SportyBet VALUES), which fuzzy-matched one club against another and could
    return a DIFFERENT team entirely — e.g. "Millwall FC" -> "AC Milan",
    "Club Brugge" -> "Cercle Brugge", "Excelsior Rotterdam" ->
    "Sparta Rotterdam". That attached one club's real price to the wrong model
    team.

    EXACT + NORMALIZED-EXACT ONLY — deliberately NO fuzzy pass (HR35). A name
    that isn't in the reverse table returns UNCHANGED so the caller reports
    NO DATA — PENDING. Attaching a real price to the wrong team is worse than
    an honest gap, so we never guess across clubs.
    """
    if sportybet_name in _MODEL_BY_SPORTYBET:
        return _MODEL_BY_SPORTYBET[sportybet_name]
    target = _normalize(sportybet_name)
    for sb_name, model_key in _MODEL_BY_SPORTYBET.items():
        if _normalize(sb_name) == target:
            return model_key
    return sportybet_name
