"""Render EUROPEAN_COMPETITIONS.md from the live source directories."""
from __future__ import annotations
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from competition_catalogue import load_catalogue, EUROPE, coverage, _odds_keys

rows = [x for x in load_catalogue() if x["country"]["name"] in EUROPE]
odds = _odds_keys()
byc: dict[str, list] = {}
for x in rows:
    byc.setdefault(x["country"]["name"], []).append(x)


def marks(c: dict) -> tuple[str, str, str]:
    hist = "FD" if c["history_fd"] else ("APIF" if c["history_apif"] else "—")
    return hist, ("yes" if c["thesportsdb"] else "—"), ("yes" if c["odds_api"] else "—")


out: list[str] = []
A = out.append
A("# European Competition Catalogue")
A("")
A("Generated by **querying** API-Football, football-data.co.uk, TheSportsDB and "
  "The Odds API. Not written from memory — every row came from a live directory. "
  "Regenerate with `python generate_catalogue_doc.py`.")
A("")
A(f"**{len(rows)} competitions across {len(byc)} countries** — "
  f"{sum(1 for x in rows if x['league']['type'] == 'League')} leagues, "
  f"{sum(1 for x in rows if x['league']['type'] == 'Cup')} cups.")
A("")
A("## Reading the coverage columns")
A("")
A("A competition needs **all three** to produce a board row. Two of three is "
  "still NO DATA — PENDING.")
A("")
A("| Column | Meaning |")
A("|---|---|")
A("| **History** | `FD` = football-data.co.uk — the best source, because it also "
  "carries the opening/closing odds the CLV backtest needs. `APIF` = API-Football "
  "— broad coverage, but the free tier stops at **2024**, so anything sourced "
  "there is ~2 seasons stale and is flagged as such on the board. |")
A("| **Fixtures** | Something to predict. Currently TheSportsDB, whose *shared "
  "test key* resolves only a handful of leagues — a personal key would widen "
  "this considerably. |")
A("| **Odds** | An entry price. Required for HR30 (numerical MES) and HR46 "
  "(CLV logging). A competition out of season simply isn't listed, so a `—` "
  "here can become `yes` once it kicks off. |")
A("")
A("> Coverage is checked against the mappings actually wired into the pipeline, "
  "and competition names are pinned to their home country — Scotland's "
  "Championship does not inherit the English Championship's sources.")
A("")
A("## Continental competitions")
A("")
A("| ID | Competition | Type | Seasons | History | Fixtures | Odds |")
A("|---|---|---|---|---|---|---|")
for x in sorted(byc.get("World", []), key=lambda x: x["league"]["id"]):
    n = x["league"]["name"]
    if not any(w in n for w in ("UEFA", "Europa", "Champions League", "Conference", "Super Cup")):
        continue
    if any(w in n for w in ("Women", "U17", "U19", "U21", "Youth")):
        continue
    yrs = [s["year"] for s in x.get("seasons", [])]
    h, f, o = marks(coverage(n, "World", odds))
    A(f"| {x['league']['id']} | {n} | {x['league']['type']} | "
      f"{min(yrs)}-{max(yrs)} | {h} | {f} | {o} |")
A("")
A("## Domestic competitions by country")
A("")
A("Showing up to 8 leagues and 4 cups per country; deeper tiers exist in the "
  "cached catalogue.")
A("")
for country in sorted(byc):
    if country == "World":
        continue
    comps = byc[country]
    lgs = sorted([x for x in comps if x["league"]["type"] == "League"],
                 key=lambda x: x["league"]["id"])
    cups = sorted([x for x in comps if x["league"]["type"] == "Cup"],
                  key=lambda x: x["league"]["id"])
    A(f"### {country} · {len(lgs)} leagues, {len(cups)} cups")
    A("")
    A("| ID | Competition | Type | Seasons | History | Fixtures | Odds |")
    A("|---|---|---|---|---|---|---|")
    for x in lgs[:8] + cups[:4]:
        n = x["league"]["name"]
        yrs = [s["year"] for s in x.get("seasons", [])]
        h, f, o = marks(coverage(n, country, odds))
        A(f"| {x['league']['id']} | {n} | {x['league']['type']} | "
          f"{min(yrs)}-{max(yrs)} | {h} | {f} | {o} |")
    A("")

Path("EUROPEAN_COMPETITIONS.md").write_text("\n".join(out), encoding="utf-8")
print(f"wrote EUROPEAN_COMPETITIONS.md — {len(out)} lines")
