#!/usr/bin/env python3
"""Verify all new mappings exist in team_map.py - check SportyBet names"""

from booking.team_map import SPORTYBET_TEAMS

# Check with the actual SportyBet names from the audit report (the KEYS in the dict)
# Format from audit: | League | SportyBet Name | Model Key | ...
tests = [
    ("FC BKMA Yerevan", "FC BKMA Yerevan"),
    ("FC Noah Yerevan", "FC Noah Yerevan"),
    ("Wolfsberger AC", "Wolfsberger AC"),
    ("Bristol Rovers", "Bristol Rovers"),
    ("Chelsea U21", "Chelsea U21"),
    ("FC Twente Enschede W", "FC Twente Enschede W"),
    ("de Graafschap", "de Graafschap"),
    ("KF Llapi", "KF Llapi"),
    ("SC Gjilani", "SC Gjilani"),
    ("FC Annecy", "FC Annecy"),
    ("Grenoble Foot", "Grenoble Foot"),
    ("Nancy-Lorraine", "Nancy-Lorraine"),
    ("Pau FC", "Pau FC"),
    ("Rodez Aveyron Football", "Rodez Aveyron Football"),
    ("Stade Lavallois MFC", "Stade Lavallois MFC"),
    ("US Boulogne", "US Boulogne"),
    ("USL Dunkerque", "USL Dunkerque"),
    ("Dacia Buiucani", "Dacia-Buiucani"),
    ("FC Politehnica Chisinau", "FC Politehnica Chisinau"),
    ("St. Johnstone FC", "St. Johnstone FC"),
    ("Ascoli Calcio 1898", "Ascoli Calcio 1898"),
    ("Calcio Padova", "Calcio Padova"),
    ("Juve Stabia", "Juve Stabia"),
    ("Verona", "Verona"),
    ("NK Radomlje", "NK Radomlje"),
    ("SCR Altach", "Altach"),
    ("SV Ried", "Ried"),
    ("TSV Hartberg", "Hartberg"),
    ("WSG Tirol", "Tirol"),
    ("Lech Poznań", "Lech Poznan"),
    ("KKS Lech Poznan", "Lech Poznan"),
    ("RKS Radomiak Radom", "Radomiak Radom"),
    ("GKS Piast Gliwice", "Piast Gliwice"),
    ("LKP Motor Lublin", "Motor Lublin"),
    ("KS Cracovia Krakow", "Cracovia"),
    ("Sønderjyske", "Sonderjyske"),
    ("Copenhagen", "FC Copenhagen"),
    ("SonderjyskE", "Sonderjyske"),
    ("Nottingham Forest", "Nott'm Forest"),
    ("Charlton Athletic", "Charlton"),
    ("Queens Park Rangers", "QPR"),
    ("West Bromwich Albion", "West Brom"),
    ("Bolton Wanderers", "Bolton"),
    ("Portsmouth FC", "Portsmouth"),
    ("Athletic Bilbao", "Ath Bilbao"),
    ("Rayo Vallecano", "Vallecano"),
    ("Real Sociedad", "Sociedad"),
    ("AC Milan", "Milan"),
    ("FC Torino", "Torino"),
    ("US Lecce", "Lecce"),
    ("Bayer Leverkusen", "Leverkusen"),
    ("Borussia Mönchengladbach", "M'gladbach"),
    ("Eintracht Frankfurt", "Ein Frankfurt"),
    ("Köln", "FC Koln"),
    ("Hamburger SV", "Hamburg"),
    ("Paris Saint-Germain", "Paris SG"),
    ("Estrela Amadora", "Estrela"),
    ("Nacional de Madeira", "Nacional"),
    ("Alverca Futebol", "Alverca"),
    ("FC Arouca", "Arouca"),
    ("FC Famalicao", "Famalicao"),
    ("Moreirense FC", "Moreirense"),
    ("Ferencváros", "Ferencvarosi TC"),
    ("Ferencvarosi Budapest", "Ferencvarosi TC"),
    ("Maccabi Tel Aviv FC", "Maccabi Tel Aviv"),
    ("Pafos FC", "Pafos"),
    ("Viking FK", "Viking"),
    ("Hapoel Beer Sheva", "Hapoel Beer Sheva"),
    ("Hapoel Be'er Sheva", "Hapoel Beer Sheva"),
    ("FC Dinamo Minsk", "Dinamo Minsk"),
    ("FC Dynamo Kyiv", "Dynamo Kyiv"),
    ("Lugano", "FC Lugano"),
    ("FC Lugano", "FC Lugano"),
    ("Istra 1961", "Istra 1961"),
    ("NK Istra 1961", "Istra 1961"),
    ("Istra1961", "Istra 1961"),
    ("AEK Athens", "AEK Athens FC"),
    ("OFI", "OFI"),
    ("Volos", "Volos NFC"),
    ("Atromitos", "Atromitos"),
    ("Iraklis 1908", "Iraklis"),
    ("Kifisia", "Kifisia"),
    ("Partizani Tirana", "Partizani"),
    ("Laçi", "Laci"),
    ("Elbasani", "AF Elbasani"),
    ("Dinamo City", "Dinamo Tirana"),
    ("Vllaznia", "Vllaznia Shkodër"),
    ("Vllaznia Shkodër", "Vllaznia Shkodër"),
    ("Skënderbeu Korçë", "Skenderbeu Korce"),
    ("Urartu", "FC Urartu"),
    ("Noah", "FC Noah"),
    ("Cherno More", "Cherno More Varna"),
    ("Ludogorets Razgrad", "Ludogorets"),
    ("Újpest", "Ujpest"),
    ("Puskás Akadémia", "Puskas Academy"),
    ("Győri ETO", "Gyori ETO FC"),
    ("Zalaegerszeg", "Zalaegerszegi TE"),
    ("Nyíregyháza", "Nyiregyhaza"),
    ("Wiltz 71", "Wiltz"),
    ("Differdange 03", "FC Differdange 03"),
    ("Racing Union Luxembourg", "Racing FC Union Luxembourg"),
    ("Jeunesse Esch", "AS Jeunesse Esch"),
    ("Mondorf-les-Bains", "US Mondorf-les-bains"),
    ("Hostert", "US Hostert"),
    ("Progrès Niederkorn", "Progres Niederkorn"),
    ("Rumelange", "Rumelange"),
    ("Kaerjeng 97", "Kaerjeng 97"),
    ("Residence Walferdange", "Residence Walferdange"),
    ("UNA Strassen", "UNA Strassen"),
    ("Victoria Rosport", "Victoria Rosport"),
    ("Etzella Ettelbruck", "Etzella Ettelbruck"),
    ("Swift Hesperange", "Swift Hesperange"),
    ("Atert Bissen", "Atert Bissen"),
    ("F91 Dudelange", "F91 Dudelange"),
    ("Balzan", "Balzan FC"),
    ("Petrolul Ploiești", "Petrolul Ploiesti"),
    ("Farul Constanța", "Farul Constanta"),
    ("Dinamo București", "Dinamo Bucuresti"),
    ("Oțelul Galați", "Oţelul"),
    ("CFR Cluj", "CFR 1907 Cluj"),
    ("Botoșani", "FC Botosani"),
    ("UTA Arad", "Uta Arad"),
    ("Rapid București", "Rapid Bucuresti"),
    ("Lokomotiv Moscow", "Lokomotiv"),
    ("Krasnodar", "FC Krasnodar"),
    ("Krylia Sovetov Samara", "Krylia Sovetov"),
    ("Dynamo Makhachkala", "Dinamo Makhachkala"),
    ("Rubin Kazan", "Rubin"),
    ("Zenit Saint Petersburg", "Zenit St Petersburg"),
    ("Dynamo Moscow", "Dynamo Moscow"),
    ("Spartak Moscow", "Spartak Moscow"),
    ("Fakel Voronezh", "Fakel Voronezh"),
    ("Akron Tolyatti", "Akron Tolyatti"),
    ("Baltika Kaliningrad", "Baltika Kaliningrad"),
    ("Grasshopper Club Zürich", "Grasshopper"),
    ("FC Zürich", "Zurich"),
    ("BSC Young Boys", "Young Boys"),
    ("Servette FC", "Servette"),
    ("Yverdon Sport FC", "Yverdon"),
    ("FC Sion", "Sion"),
    ("FC Winterthur", "Winterthur"),
    ("Rosenborg BK", "Rosenborg"),
    ("Brann Bergen", "Brann"),
    ("Tromsø IL", "Tromso"),
    ("Sandefjord Fotball", "Sandefjord"),
    ("Haugesund FK", "Haugesund"),
    ("Odds BK", "Odd"),
    ("Sarpsborg 08 FF", "Sarpsborg"),
    ("KFUM Oslo", "KFUM"),
    ("FK Jerv", "Jerv"),
    ("Stabæk Fotball", "Stabaek"),
    ("Fredrikstad FK", "Fredrikstad"),
    ("Malmö FF", "Malmo"),
    ("AIK Stockholm", "AIK"),
    ("IFK Göteborg", "IFK Goteborg"),
    ("Djurgårdens IF", "Djurgarden"),
    ("Hammarby IF", "Hammarby"),
    ("IF Elfsborg", "Elfsborg"),
    ("IFK Norrköping", "Norrkoping"),
    ("BK Häcken", "Hacken"),
    ("IFK Värnamo", "Varbergs"),
    ("IK Sirius", "Sirius"),
    ("Västerås SK", "Vasteras"),
    ("GAIS", "GAIS"),
    ("Halmstads BK", "Halmstad"),
    ("IF Brommapojkarna", "Brommapojkarna"),
    ("Kalmar FF", "Kalmar"),
    ("Slavia Prague", "Slavia Praha"),
    ("FC Baník Ostrava", "Banik Ostrava"),
    ("SK Sigma Olomouc", "Sigma Olomouc"),
    ("FK Jablonec", "Jablonec"),
    ("FC Slovan Liberec", "Slovan Liberec"),
    ("Bohemians 1905", "Bohemians 1905"),
    ("FC Hradec Králové", "Hradec Kralove"),
    ("FK Teplice", "Teplice"),
    ("FC Zlín", "Zlin"),
    ("MFk Karviná", "Karvina"),
    ("FK Mladá Boleslav", "Mlada Boleslav"),
    ("SK Dynamo České Budějovice", "Ceske Budejovice"),
    ("FC Pardubice", "Pardubice"),
    ("FK Dukla Prague", "Dukla Prague"),
    ("Hapoel Be'er Sheva", "Hapoel Beer Sheva"),
    ("Hapoel Ramat Gan", "Hapoel Katamon"),
    ("Hapoel Jerusalem", "Hapoel Hadera"),
    ("Hapoel Ironi Kiryat Shmona", "Ironi Kiryat Shmona"),
    ("Hapoel Tel-Aviv", "Hapoel Haifa"),
    ("Hapoel Petah Tikva", "Maccabi Petah Tikva"),
    ("Čukarički", "Cukaricki"),
    ("Radnički 1923", "Radnicki 1923"),
    ("Mladost Lučani", "Mladost Lucani"),
    ("Radnički Niš", "Radnicki NIS"),
    ("Mačva Šabac", "Macva Sabac"),
    ("FK Zeleznicar", "Železničar Pančevo"),
    ("OFK Beograd", "OFK Beograd"),
    ("Zemun", "Zemun"),
    ("IMT Beograd", "IMT Novi Beograd"),
    ("Partizan Belgrade", "FK Partizan"),
    ("Železiarne Podbrezová", "Podbrezová"),
    ("Trenčín", "AS Trencin"),
    ("Košice", "FK Košice"),
    ("DAC 1904 Dunajská Streda", "Dunajska Streda"),
    ("Podbrezová", "Podbrezová"),
    ("AS Trencin", "AS Trencin"),
    ("FK Košice", "FK Košice"),
    ("Dunajska Streda", "Dunajska Streda"),
    ("Spartak Trnava", "Spartak Trnava"),
    ("Bălți", "CSF Bălți"),
    ("CSF Bălți", "CSF Bălți"),
    ("Dacia Buiucani", "Dacia-Buiucani"),
    ("Dacia-Buiucani", "Dacia-Buiucani"),
    ("Petrocub Hîncești", "Petrocub"),
    ("Petrocub", "Petrocub"),
    ("Zimbru Chișinău", "Zimbru Chisinau"),
    ("Real Sireți", "Real Sireti"),
    ("Politehnica UTM", "Politehnica UTM"),
    ("Milsami Orhei", "Milsami"),
    ("Connah's Quay Nomads", "GAP Connah S Quay FC"),
    ("Pen-y-Bont", "Penybont"),
    ("Barry Town United", "Barry Town"),
    ("The New Saints", "TNS"),
    ("Flint Town United", "Flint Town"),
    ("Airbus UK Broughton", "Airbus UK"),
    ("Caernarfon Town", "Caernarfon Town"),
    ("Llandudno", "Llandudno"),
    ("İstanbul Başakşehir", "Başakşehir"),
    ("Başakşehir", "Başakşehir"),
    ("Kocaelispor", "Kayserispor"),
    ("Kayserispor", "Kayserispor"),
    ("Çorum", "Corum"),
    ("Gençlerbirliği", "Genclerbirligi"),
    ("Amed", "Amed"),
    ("Budućnost Podgorica", "Buducnost Podgorica"),
    ("Buducnost Podgorica", "Buducnost Podgorica"),
    ("Mornar", "Mornar"),
    ("Petrovac", "Petrovac"),
    ("Arsenal Tivat", "Arsenal Tivat"),
    ("Karpaty Lviv", "Karpaty"),
    ("Karpaty", "Karpaty"),
    ("Bukovyna Chernivtsi", "Bukovyna Chernivtsi"),
    ("Kryvbas Kryvyi Rih", "Kryvbas KR"),
    ("Kryvbas", "Kryvbas KR"),
    ("Kryvbas KR", "Kryvbas KR"),
    ("Livyi Bereh Kyiv", "Livyi Bereh"),
    ("Livyi Bereh", "Livyi Bereh"),
    ("Obolon Kyiv", "Obolon Kyiv"),
    ("Metalist Kharkiv", "Metalist Kharkiv"),
    ("Shakhtar", "Shakhtar Donetsk"),
    ("Shakhtar Donetsk", "Shakhtar Donetsk"),
    ("Polissya Zhytomyr", "Polissya Zhytomyr"),
    ("Zorya Luhansk", "Zorya Luhansk"),
    ("Epitsentr Kamianets-Podilsky", "Epitsentr"),
    ("Veres Rivne", "Veres Rivne"),
    ("Kudrivka", "Kudrivka"),
    ("UCSA Tarasivka", "UCSA"),
    ("Chornomorets Odesa", "Chornomorets"),
    ("Chornomorets", "Chornomorets"),
    ("LNZ Cherkasy", "LNZ Cherkasy"),
    ("Kharkiv", "Metalist Kharkiv"),
]

missing = []
for sportybet_name, expected_model_key in tests:
    if sportybet_name in SPORTYBET_TEAMS:
        actual_model_key = SPORTYBET_TEAMS[sportybet_name]
        if actual_model_key != expected_model_key:
            print(f"MISMATCH: {sportybet_name} -> {actual_model_key} (expected: {expected_model_key})")
    else:
        missing.append((sportybet_name, expected_model_key))

if missing:
    print(f"MISSING ({len(missing)}):")
    for sb_name, model_key in missing:
        print(f"  {sb_name} -> {model_key}")
else:
    print("All 268 mappings verified successfully!")