tier1:
  - id: KY7LrA6d
    country: Germany
    league: Bundesliga
    season_seen: jg0MwVuC

  - id: WdNk9YwP
    country: Italy
    league: Serie A
    season_seen: CfujcOgK

  - id: QeI1Oeyi
    country: Spain
    league: LaLiga
    season_seen: dWdJXP6U

  - id: 0Mp0HlJb
    country: France
    league: Ligue 1
    season_seen: CQF28KxR

  - id: nHciQpuf
    country: Netherlands
    league: Eredivisie
    season_seen: zm1be8bD

  - id: QNIOJe2e
    country: Belgium
    league: Jupiler Pro League
    season_seen: MFaWsPnS

  - id: ULABWQN9
    country: Denmark
    league: Superliga
    season_seen: b3gDmFWi

  - id: 8rEt4Zsf
    country: Austria
    league: Bundesliga
    season_seen: GbYvzOTG

  - id: Q74g9dNP
    country: England
    league: Championship
    season_seen: 40zsPsC5